# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_nbn.ui'
#
# Created: Mon Mar 27 17:47:40 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_nbn(object):
    def setupUi(self, nbn):
        nbn.setObjectName(_fromUtf8("nbn"))
        nbn.resize(407, 560)
        nbn.setStyleSheet(_fromUtf8("#pbAttention{\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 12px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"#pbAttention:pressed {\n"
"    background-color: rgb(224, 0, 0);\n"
"    border-style: inset;\n"
"}"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(nbn)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tabWidget = QtGui.QTabWidget(nbn)
        self.tabWidget.setMinimumSize(QtCore.QSize(280, 230))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabOptions = QtGui.QWidget()
        self.tabOptions.setObjectName(_fromUtf8("tabOptions"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tabOptions)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cbGridSize = QtGui.QComboBox(self.groupBox_3)
        self.cbGridSize.setMinimumSize(QtCore.QSize(90, 28))
        self.cbGridSize.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cbGridSize.setObjectName(_fromUtf8("cbGridSize"))
        self.cbGridSize.addItem(_fromUtf8(""))
        self.cbGridSize.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cbGridSize)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.hsTransparency = QtGui.QSlider(self.groupBox_3)
        self.hsTransparency.setProperty("value", 0)
        self.hsTransparency.setOrientation(QtCore.Qt.Horizontal)
        self.hsTransparency.setTickPosition(QtGui.QSlider.TicksBelow)
        self.hsTransparency.setTickInterval(10)
        self.hsTransparency.setObjectName(_fromUtf8("hsTransparency"))
        self.horizontalLayout_3.addWidget(self.hsTransparency)
        self.cbOutline = QtGui.QCheckBox(self.groupBox_3)
        self.cbOutline.setObjectName(_fromUtf8("cbOutline"))
        self.horizontalLayout_3.addWidget(self.cbOutline)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.pbSpeciesWMS = QtGui.QPushButton(self.groupBox_3)
        self.pbSpeciesWMS.setMinimumSize(QtCore.QSize(90, 28))
        self.pbSpeciesWMS.setMaximumSize(QtCore.QSize(90, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/nbngridmap.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSpeciesWMS.setIcon(icon)
        self.pbSpeciesWMS.setIconSize(QtCore.QSize(20, 20))
        self.pbSpeciesWMS.setObjectName(_fromUtf8("pbSpeciesWMS"))
        self.horizontalLayout_13.addWidget(self.pbSpeciesWMS)
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.butClearLast = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butClearLast.sizePolicy().hasHeightForWidth())
        self.butClearLast.setSizePolicy(sizePolicy)
        self.butClearLast.setMinimumSize(QtCore.QSize(30, 30))
        self.butClearLast.setMaximumSize(QtCore.QSize(30, 30))
        self.butClearLast.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/removelayer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butClearLast.setIcon(icon1)
        self.butClearLast.setIconSize(QtCore.QSize(28, 28))
        self.butClearLast.setObjectName(_fromUtf8("butClearLast"))
        self.horizontalLayout_13.addWidget(self.butClearLast)
        self.butClear = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butClear.sizePolicy().hasHeightForWidth())
        self.butClear.setSizePolicy(sizePolicy)
        self.butClear.setMinimumSize(QtCore.QSize(30, 30))
        self.butClear.setMaximumSize(QtCore.QSize(30, 30))
        self.butClear.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/removelayers.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butClear.setIcon(icon2)
        self.butClear.setIconSize(QtCore.QSize(28, 28))
        self.butClear.setObjectName(_fromUtf8("butClear"))
        self.horizontalLayout_13.addWidget(self.butClear)
        self.butHelp = QtGui.QPushButton(self.groupBox_3)
        self.butHelp.setMinimumSize(QtCore.QSize(30, 30))
        self.butHelp.setMaximumSize(QtCore.QSize(30, 30))
        self.butHelp.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/bang.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butHelp.setIcon(icon3)
        self.butHelp.setIconSize(QtCore.QSize(24, 24))
        self.butHelp.setObjectName(_fromUtf8("butHelp"))
        self.horizontalLayout_13.addWidget(self.butHelp)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(self.tabOptions)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.pbDownload = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbDownload.sizePolicy().hasHeightForWidth())
        self.pbDownload.setSizePolicy(sizePolicy)
        self.pbDownload.setMinimumSize(QtCore.QSize(100, 28))
        self.pbDownload.setMaximumSize(QtCore.QSize(90, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("images/nbndownload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbDownload.setIcon(icon4)
        self.pbDownload.setIconSize(QtCore.QSize(20, 20))
        self.pbDownload.setObjectName(_fromUtf8("pbDownload"))
        self.horizontalLayout_14.addWidget(self.pbDownload)
        spacerItem1 = QtGui.QSpacerItem(96, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout_11.addWidget(self.groupBox_5)
        self.groupBox_7 = QtGui.QGroupBox(self.tabOptions)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.cbIndTaxon = QtGui.QCheckBox(self.groupBox_7)
        self.cbIndTaxon.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndTaxon.sizePolicy().hasHeightForWidth())
        self.cbIndTaxon.setSizePolicy(sizePolicy)
        self.cbIndTaxon.setMinimumSize(QtCore.QSize(70, 0))
        self.cbIndTaxon.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbIndTaxon.setObjectName(_fromUtf8("cbIndTaxon"))
        self.horizontalLayout_19.addWidget(self.cbIndTaxon)
        self.cbIndGroup = QtGui.QCheckBox(self.groupBox_7)
        self.cbIndGroup.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndGroup.sizePolicy().hasHeightForWidth())
        self.cbIndGroup.setSizePolicy(sizePolicy)
        self.cbIndGroup.setMinimumSize(QtCore.QSize(80, 0))
        self.cbIndGroup.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cbIndGroup.setObjectName(_fromUtf8("cbIndGroup"))
        self.horizontalLayout_19.addWidget(self.cbIndGroup)
        self.cbIndDesignation = QtGui.QCheckBox(self.groupBox_7)
        self.cbIndDesignation.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndDesignation.sizePolicy().hasHeightForWidth())
        self.cbIndDesignation.setSizePolicy(sizePolicy)
        self.cbIndDesignation.setMinimumSize(QtCore.QSize(80, 0))
        self.cbIndDesignation.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cbIndDesignation.setObjectName(_fromUtf8("cbIndDesignation"))
        self.horizontalLayout_19.addWidget(self.cbIndDesignation)
        self.cbIndAbsence = QtGui.QCheckBox(self.groupBox_7)
        self.cbIndAbsence.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndAbsence.sizePolicy().hasHeightForWidth())
        self.cbIndAbsence.setSizePolicy(sizePolicy)
        self.cbIndAbsence.setMinimumSize(QtCore.QSize(70, 0))
        self.cbIndAbsence.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbIndAbsence.setObjectName(_fromUtf8("cbIndAbsence"))
        self.horizontalLayout_19.addWidget(self.cbIndAbsence)
        spacerItem2 = QtGui.QSpacerItem(8, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.cbIndDataset = QtGui.QCheckBox(self.groupBox_7)
        self.cbIndDataset.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndDataset.sizePolicy().hasHeightForWidth())
        self.cbIndDataset.setSizePolicy(sizePolicy)
        self.cbIndDataset.setMinimumSize(QtCore.QSize(70, 0))
        self.cbIndDataset.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbIndDataset.setObjectName(_fromUtf8("cbIndDataset"))
        self.horizontalLayout_20.addWidget(self.cbIndDataset)
        self.cbIndStartYear = QtGui.QCheckBox(self.groupBox_7)
        self.cbIndStartYear.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndStartYear.sizePolicy().hasHeightForWidth())
        self.cbIndStartYear.setSizePolicy(sizePolicy)
        self.cbIndStartYear.setMinimumSize(QtCore.QSize(80, 0))
        self.cbIndStartYear.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cbIndStartYear.setObjectName(_fromUtf8("cbIndStartYear"))
        self.horizontalLayout_20.addWidget(self.cbIndStartYear)
        self.cbIndEndYear = QtGui.QCheckBox(self.groupBox_7)
        self.cbIndEndYear.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndEndYear.sizePolicy().hasHeightForWidth())
        self.cbIndEndYear.setSizePolicy(sizePolicy)
        self.cbIndEndYear.setMinimumSize(QtCore.QSize(80, 0))
        self.cbIndEndYear.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cbIndEndYear.setObjectName(_fromUtf8("cbIndEndYear"))
        self.horizontalLayout_20.addWidget(self.cbIndEndYear)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_14.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.cbIndPolygon = QtGui.QCheckBox(self.groupBox_7)
        self.cbIndPolygon.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndPolygon.sizePolicy().hasHeightForWidth())
        self.cbIndPolygon.setSizePolicy(sizePolicy)
        self.cbIndPolygon.setMinimumSize(QtCore.QSize(70, 0))
        self.cbIndPolygon.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbIndPolygon.setObjectName(_fromUtf8("cbIndPolygon"))
        self.horizontalLayout_21.addWidget(self.cbIndPolygon)
        self.cbIndSite = QtGui.QCheckBox(self.groupBox_7)
        self.cbIndSite.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndSite.sizePolicy().hasHeightForWidth())
        self.cbIndSite.setSizePolicy(sizePolicy)
        self.cbIndSite.setMinimumSize(QtCore.QSize(80, 0))
        self.cbIndSite.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cbIndSite.setObjectName(_fromUtf8("cbIndSite"))
        self.horizontalLayout_21.addWidget(self.cbIndSite)
        self.cbIndGridRef = QtGui.QCheckBox(self.groupBox_7)
        self.cbIndGridRef.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndGridRef.sizePolicy().hasHeightForWidth())
        self.cbIndGridRef.setSizePolicy(sizePolicy)
        self.cbIndGridRef.setMinimumSize(QtCore.QSize(80, 0))
        self.cbIndGridRef.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cbIndGridRef.setObjectName(_fromUtf8("cbIndGridRef"))
        self.horizontalLayout_21.addWidget(self.cbIndGridRef)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_21)
        self.verticalLayout_11.addWidget(self.groupBox_7)
        spacerItem5 = QtGui.QSpacerItem(20, 23, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.tabWidget.addTab(self.tabOptions, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_7)
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.tab_8)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leTaxonSearch = QtGui.QLineEdit(self.tab_8)
        self.leTaxonSearch.setObjectName(_fromUtf8("leTaxonSearch"))
        self.horizontalLayout.addWidget(self.leTaxonSearch)
        self.butTaxonSearch = QtGui.QPushButton(self.tab_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butTaxonSearch.sizePolicy().hasHeightForWidth())
        self.butTaxonSearch.setSizePolicy(sizePolicy)
        self.butTaxonSearch.setMinimumSize(QtCore.QSize(30, 30))
        self.butTaxonSearch.setMaximumSize(QtCore.QSize(30, 30))
        self.butTaxonSearch.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("images/speciesinventory.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butTaxonSearch.setIcon(icon5)
        self.butTaxonSearch.setIconSize(QtCore.QSize(26, 26))
        self.butTaxonSearch.setObjectName(_fromUtf8("butTaxonSearch"))
        self.horizontalLayout.addWidget(self.butTaxonSearch)
        self.verticalLayout_19.addLayout(self.horizontalLayout)
        self.twTaxa = QtGui.QTreeWidget(self.tab_8)
        self.twTaxa.setIndentation(10)
        self.twTaxa.setHeaderHidden(True)
        self.twTaxa.setColumnCount(1)
        self.twTaxa.setObjectName(_fromUtf8("twTaxa"))
        self.twTaxa.headerItem().setText(0, _fromUtf8("1"))
        self.twTaxa.header().setVisible(False)
        self.twTaxa.header().setStretchLastSection(True)
        self.verticalLayout_19.addWidget(self.twTaxa)
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_9)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.twDatasets = QtGui.QTreeWidget(self.tab_9)
        self.twDatasets.setHeaderHidden(True)
        self.twDatasets.setColumnCount(1)
        self.twDatasets.setObjectName(_fromUtf8("twDatasets"))
        self.twDatasets.headerItem().setText(0, _fromUtf8("1"))
        self.twDatasets.header().setVisible(False)
        self.twDatasets.header().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.twDatasets)
        self.lblDatasetFilter = QtGui.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblDatasetFilter.setFont(font)
        self.lblDatasetFilter.setAutoFillBackground(False)
        self.lblDatasetFilter.setWordWrap(True)
        self.lblDatasetFilter.setObjectName(_fromUtf8("lblDatasetFilter"))
        self.verticalLayout_4.addWidget(self.lblDatasetFilter)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.pbUncheckAll = QtGui.QPushButton(self.tab_9)
        self.pbUncheckAll.setMinimumSize(QtCore.QSize(65, 0))
        self.pbUncheckAll.setMaximumSize(QtCore.QSize(65, 16777215))
        self.pbUncheckAll.setObjectName(_fromUtf8("pbUncheckAll"))
        self.horizontalLayout_9.addWidget(self.pbUncheckAll)
        self.pbRefreshDatasets = QtGui.QPushButton(self.tab_9)
        self.pbRefreshDatasets.setObjectName(_fromUtf8("pbRefreshDatasets"))
        self.horizontalLayout_9.addWidget(self.pbRefreshDatasets)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.tabWidget_2.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_10)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.splitter_2 = QtGui.QSplitter(self.tab_10)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget_4 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_15.addWidget(self.label_5)
        self.twAreaCategories = QtGui.QTreeWidget(self.layoutWidget_4)
        self.twAreaCategories.setHeaderHidden(True)
        self.twAreaCategories.setColumnCount(1)
        self.twAreaCategories.setObjectName(_fromUtf8("twAreaCategories"))
        self.twAreaCategories.headerItem().setText(0, _fromUtf8("1"))
        self.twAreaCategories.header().setVisible(False)
        self.twAreaCategories.header().setStretchLastSection(True)
        self.verticalLayout_15.addWidget(self.twAreaCategories)
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.lblSiteDataset = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSiteDataset.sizePolicy().hasHeightForWidth())
        self.lblSiteDataset.setSizePolicy(sizePolicy)
        self.lblSiteDataset.setMinimumSize(QtCore.QSize(0, 0))
        self.lblSiteDataset.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblSiteDataset.setWordWrap(True)
        self.lblSiteDataset.setObjectName(_fromUtf8("lblSiteDataset"))
        self.verticalLayout_13.addWidget(self.lblSiteDataset)
        self.twAreas = QtGui.QTreeWidget(self.layoutWidget)
        self.twAreas.setHeaderHidden(True)
        self.twAreas.setColumnCount(1)
        self.twAreas.setObjectName(_fromUtf8("twAreas"))
        self.twAreas.headerItem().setText(0, _fromUtf8("1"))
        self.twAreas.header().setVisible(False)
        self.twAreas.header().setStretchLastSection(True)
        self.verticalLayout_13.addWidget(self.twAreas)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem7)
        self.pbRefreshAreas = QtGui.QPushButton(self.layoutWidget)
        self.pbRefreshAreas.setObjectName(_fromUtf8("pbRefreshAreas"))
        self.horizontalLayout_18.addWidget(self.pbRefreshAreas)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.verticalLayout_7.addWidget(self.splitter_2)
        self.tabWidget_2.addTab(self.tab_10, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab_11)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.twDesignations = QtGui.QTreeWidget(self.tab_11)
        self.twDesignations.setHeaderHidden(True)
        self.twDesignations.setColumnCount(1)
        self.twDesignations.setObjectName(_fromUtf8("twDesignations"))
        self.twDesignations.headerItem().setText(0, _fromUtf8("1"))
        self.twDesignations.header().setVisible(False)
        self.twDesignations.header().setStretchLastSection(True)
        self.verticalLayout_16.addWidget(self.twDesignations)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.pbRefreshDesignations = QtGui.QPushButton(self.tab_11)
        self.pbRefreshDesignations.setObjectName(_fromUtf8("pbRefreshDesignations"))
        self.horizontalLayout_12.addWidget(self.pbRefreshDesignations)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.tabWidget_2.addTab(self.tab_11, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_12)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.twGroups = QtGui.QTreeWidget(self.tab_12)
        self.twGroups.setHeaderHidden(True)
        self.twGroups.setColumnCount(1)
        self.twGroups.setObjectName(_fromUtf8("twGroups"))
        self.twGroups.headerItem().setText(0, _fromUtf8("1"))
        self.twGroups.header().setVisible(False)
        self.twGroups.header().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.twGroups)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.pbRefreshGroups = QtGui.QPushButton(self.tab_12)
        self.pbRefreshGroups.setObjectName(_fromUtf8("pbRefreshGroups"))
        self.horizontalLayout_17.addWidget(self.pbRefreshGroups)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.tabWidget_2.addTab(self.tab_12, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_13)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.tab_13)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.sbStartYear = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbStartYear.sizePolicy().hasHeightForWidth())
        self.sbStartYear.setSizePolicy(sizePolicy)
        self.sbStartYear.setMinimumSize(QtCore.QSize(60, 0))
        self.sbStartYear.setMinimum(1600)
        self.sbStartYear.setMaximum(2100)
        self.sbStartYear.setSingleStep(1)
        self.sbStartYear.setProperty("value", 2000)
        self.sbStartYear.setObjectName(_fromUtf8("sbStartYear"))
        self.horizontalLayout_6.addWidget(self.sbStartYear)
        self.cbStartYear = QtGui.QCheckBox(self.groupBox)
        self.cbStartYear.setObjectName(_fromUtf8("cbStartYear"))
        self.horizontalLayout_6.addWidget(self.cbStartYear)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.sbEndYear = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbEndYear.sizePolicy().hasHeightForWidth())
        self.sbEndYear.setSizePolicy(sizePolicy)
        self.sbEndYear.setMinimumSize(QtCore.QSize(60, 0))
        self.sbEndYear.setMinimum(1600)
        self.sbEndYear.setMaximum(2100)
        self.sbEndYear.setSingleStep(1)
        self.sbEndYear.setProperty("value", 2000)
        self.sbEndYear.setObjectName(_fromUtf8("sbEndYear"))
        self.horizontalLayout_7.addWidget(self.sbEndYear)
        self.cbEndYear = QtGui.QCheckBox(self.groupBox)
        self.cbEndYear.setObjectName(_fromUtf8("cbEndYear"))
        self.horizontalLayout_7.addWidget(self.cbEndYear)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_13)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.rbPresence = QtGui.QRadioButton(self.groupBox_2)
        self.rbPresence.setChecked(True)
        self.rbPresence.setObjectName(_fromUtf8("rbPresence"))
        self.horizontalLayout_8.addWidget(self.rbPresence)
        self.rbAbsence = QtGui.QRadioButton(self.groupBox_2)
        self.rbAbsence.setObjectName(_fromUtf8("rbAbsence"))
        self.horizontalLayout_8.addWidget(self.rbAbsence)
        spacerItem10 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_13)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.leGridRef = QtGui.QLineEdit(self.groupBox_6)
        self.leGridRef.setObjectName(_fromUtf8("leGridRef"))
        self.horizontalLayout_23.addWidget(self.leGridRef)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        spacerItem11 = QtGui.QSpacerItem(17, 53, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem11)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_13)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.rbGR = QtGui.QRadioButton(self.groupBox_8)
        self.rbGR.setChecked(True)
        self.rbGR.setObjectName(_fromUtf8("rbGR"))
        self.horizontalLayout_24.addWidget(self.rbGR)
        self.rbEN = QtGui.QRadioButton(self.groupBox_8)
        self.rbEN.setObjectName(_fromUtf8("rbEN"))
        self.horizontalLayout_24.addWidget(self.rbEN)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lePointBufferGR = QtGui.QLineEdit(self.groupBox_8)
        self.lePointBufferGR.setObjectName(_fromUtf8("lePointBufferGR"))
        self.horizontalLayout_4.addWidget(self.lePointBufferGR)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.sbEasting = QtGui.QSpinBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbEasting.sizePolicy().hasHeightForWidth())
        self.sbEasting.setSizePolicy(sizePolicy)
        self.sbEasting.setMinimumSize(QtCore.QSize(60, 0))
        self.sbEasting.setMinimum(0)
        self.sbEasting.setMaximum(2000000)
        self.sbEasting.setSingleStep(1000)
        self.sbEasting.setProperty("value", 0)
        self.sbEasting.setObjectName(_fromUtf8("sbEasting"))
        self.horizontalLayout_10.addWidget(self.sbEasting)
        self.label_8 = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.sbNorthing = QtGui.QSpinBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbNorthing.sizePolicy().hasHeightForWidth())
        self.sbNorthing.setSizePolicy(sizePolicy)
        self.sbNorthing.setMinimumSize(QtCore.QSize(60, 0))
        self.sbNorthing.setMinimum(0)
        self.sbNorthing.setMaximum(2000000)
        self.sbNorthing.setSingleStep(1000)
        self.sbNorthing.setProperty("value", 0)
        self.sbNorthing.setObjectName(_fromUtf8("sbNorthing"))
        self.horizontalLayout_10.addWidget(self.sbNorthing)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_9 = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_22.addWidget(self.label_9)
        self.sbBuffer = QtGui.QSpinBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbBuffer.sizePolicy().hasHeightForWidth())
        self.sbBuffer.setSizePolicy(sizePolicy)
        self.sbBuffer.setMinimumSize(QtCore.QSize(60, 0))
        self.sbBuffer.setMinimum(10)
        self.sbBuffer.setMaximum(10000)
        self.sbBuffer.setSingleStep(10)
        self.sbBuffer.setProperty("value", 2000)
        self.sbBuffer.setObjectName(_fromUtf8("sbBuffer"))
        self.horizontalLayout_22.addWidget(self.sbBuffer)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem13)
        self.pbBuffer = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbBuffer.sizePolicy().hasHeightForWidth())
        self.pbBuffer.setSizePolicy(sizePolicy)
        self.pbBuffer.setMinimumSize(QtCore.QSize(30, 30))
        self.pbBuffer.setMaximumSize(QtCore.QSize(30, 30))
        self.pbBuffer.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("images/buffer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbBuffer.setIcon(icon6)
        self.pbBuffer.setIconSize(QtCore.QSize(26, 26))
        self.pbBuffer.setObjectName(_fromUtf8("pbBuffer"))
        self.horizontalLayout_22.addWidget(self.pbBuffer)
        self.pbClearLastBuffer = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClearLastBuffer.sizePolicy().hasHeightForWidth())
        self.pbClearLastBuffer.setSizePolicy(sizePolicy)
        self.pbClearLastBuffer.setMinimumSize(QtCore.QSize(30, 30))
        self.pbClearLastBuffer.setMaximumSize(QtCore.QSize(30, 30))
        self.pbClearLastBuffer.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("images/bufferclear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClearLastBuffer.setIcon(icon7)
        self.pbClearLastBuffer.setIconSize(QtCore.QSize(26, 26))
        self.pbClearLastBuffer.setObjectName(_fromUtf8("pbClearLastBuffer"))
        self.horizontalLayout_22.addWidget(self.pbClearLastBuffer)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.verticalLayout_6.addWidget(self.groupBox_8)
        self.tabWidget_2.addTab(self.tab_13, _fromUtf8(""))
        self.verticalLayout_18.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.lwDownloaded = QtGui.QListWidget(self.tab_4)
        self.lwDownloaded.setObjectName(_fromUtf8("lwDownloaded"))
        self.verticalLayout_10.addWidget(self.lwDownloaded)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem14)
        self.pbSendToBiorec = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSendToBiorec.sizePolicy().hasHeightForWidth())
        self.pbSendToBiorec.setSizePolicy(sizePolicy)
        self.pbSendToBiorec.setMinimumSize(QtCore.QSize(32, 32))
        self.pbSendToBiorec.setMaximumSize(QtCore.QSize(32, 32))
        self.pbSendToBiorec.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("images/maptaxa.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSendToBiorec.setIcon(icon8)
        self.pbSendToBiorec.setIconSize(QtCore.QSize(30, 30))
        self.pbSendToBiorec.setObjectName(_fromUtf8("pbSendToBiorec"))
        self.horizontalLayout_16.addWidget(self.pbSendToBiorec)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_9.addWidget(self.tabWidget)

        self.retranslateUi(nbn)
        self.tabWidget.setCurrentIndex(0)
        self.cbGridSize.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(nbn)

    def retranslateUi(self, nbn):
        nbn.setWindowTitle(_translate("nbn", "TomBio", None))
        self.groupBox_3.setTitle(_translate("nbn", "NBN Atlas Map (WMS)", None))
        self.cbGridSize.setToolTip(_translate("nbn", "<html><head/><body><p>Points for each record or grid squares?</p></body></html>", None))
        self.cbGridSize.setItemText(0, _translate("nbn", "Record points", None))
        self.cbGridSize.setItemText(1, _translate("nbn", "Atlas squares", None))
        self.label.setText(_translate("nbn", "Transparency:", None))
        self.hsTransparency.setToolTip(_translate("nbn", "Set transparency of layer to be created", None))
        self.cbOutline.setText(_translate("nbn", "Outline", None))
        self.pbSpeciesWMS.setToolTip(_translate("nbn", "<html><head/><body><p>Fetch species distribution map from NBN Web Mapping Service. You can also apply dataset, date and presence/absence filters for this service. More than one dataset can be used in filter.</p></body></html>", None))
        self.pbSpeciesWMS.setText(_translate("nbn", "Map", None))
        self.butClearLast.setToolTip(_translate("nbn", "Remove last NBN map", None))
        self.butClear.setToolTip(_translate("nbn", "Remove all NBN maps", None))
        self.butHelp.setToolTip(_translate("nbn", "Tips and help", None))
        self.groupBox_5.setTitle(_translate("nbn", "NBN Records Download", None))
        self.pbDownload.setToolTip(_translate("nbn", "<html><head/><body><p>Download observation records from the NBN Gateway. You must specify at least one of the following filters: taxon, dataset, polygon, Site or grid reference.</p></body></html>", None))
        self.pbDownload.setText(_translate("nbn", "Download   ", None))
        self.groupBox_7.setTitle(_translate("nbn", "Specified Filters", None))
        self.cbIndTaxon.setText(_translate("nbn", "Species", None))
        self.cbIndGroup.setText(_translate("nbn", "Taxon group", None))
        self.cbIndDesignation.setText(_translate("nbn", "Designation", None))
        self.cbIndAbsence.setText(_translate("nbn", "Absence", None))
        self.cbIndDataset.setText(_translate("nbn", "Dataset", None))
        self.cbIndStartYear.setText(_translate("nbn", "Start year", None))
        self.cbIndEndYear.setText(_translate("nbn", "End year", None))
        self.cbIndPolygon.setText(_translate("nbn", "Polygon", None))
        self.cbIndSite.setText(_translate("nbn", "Site", None))
        self.cbIndGridRef.setText(_translate("nbn", "Grid ref", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOptions), _translate("nbn", "NBN", None))
        self.leTaxonSearch.setToolTip(_translate("nbn", "Enter search term for taxon", None))
        self.butTaxonSearch.setToolTip(_translate("nbn", "Search the UK Species Inventory", None))
        self.twTaxa.setToolTip(_translate("nbn", "<html><head/><body><p>Matching taxa - check TVK corresponding to species you want.</p></body></html>", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("nbn", "Taxon", None))
        self.twDatasets.setToolTip(_translate("nbn", "<html><head/><body><p>NBN Datasets - check to filter</p></body></html>", None))
        self.lblDatasetFilter.setText(_translate("nbn", "lblDatasetFilter", None))
        self.pbUncheckAll.setToolTip(_translate("nbn", "Uncheck all items", None))
        self.pbUncheckAll.setText(_translate("nbn", "Uncheck all", None))
        self.pbRefreshDatasets.setToolTip(_translate("nbn", "<html><head/><body><p>Update the dataset list from the NBN Gateway</p></body></html>", None))
        self.pbRefreshDatasets.setText(_translate("nbn", "Refresh from NBN", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("nbn", "Dataset", None))
        self.label_5.setText(_translate("nbn", "<html><head/><body><p>Double-click a site dataset to list sites for it:</p></body></html>", None))
        self.twAreaCategories.setToolTip(_translate("nbn", "<html><head/><body><p>NBN Site datasets. Double-click a dataset to see the corresponding list of sites.</p></body></html>", None))
        self.lblSiteDataset.setText(_translate("nbn", "lblSiteDataset", None))
        self.twAreas.setToolTip(_translate("nbn", "<html><head/><body><p>Sites for the selected NBN Site dataset. Check a single site to use it as a filter when yo download records from the NBN.</p></body></html>", None))
        self.pbRefreshAreas.setToolTip(_translate("nbn", "<html><head/><body><p>Refreshing the list of NBN site datasets and, if selected, a specific site dataset to ensures that you have the latest available data from the NBN Gateway.</p></body></html>", None))
        self.pbRefreshAreas.setText(_translate("nbn", "Refresh from NBN", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("nbn", "Site", None))
        self.twDesignations.setToolTip(_translate("nbn", "<html><head/><body><p>Check a designation to use it as a filter when you download records from the NBN.</p></body></html>", None))
        self.pbRefreshDesignations.setToolTip(_translate("nbn", "<html><head/><body><p>Refresh the list of designations from the NBN.</p></body></html>", None))
        self.pbRefreshDesignations.setText(_translate("nbn", "Refresh from NBN", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("nbn", "Designation", None))
        self.twGroups.setToolTip(_translate("nbn", "<html><head/><body><p>Check a taxon output group to limit a download of records from the NBN to that taxonomic group.</p></body></html>", None))
        self.pbRefreshGroups.setToolTip(_translate("nbn", "<html><head/><body><p>Get the latest list of taxon output groups from the NBN.</p></body></html>", None))
        self.pbRefreshGroups.setText(_translate("nbn", "Refresh from NBN", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_12), _translate("nbn", "Group", None))
        self.groupBox.setTitle(_translate("nbn", "Date", None))
        self.sbStartYear.setToolTip(_translate("nbn", "Specify start year", None))
        self.cbStartYear.setToolTip(_translate("nbn", "<html><head/><body><p>Check box to filter out records before given start year.</p></body></html>", None))
        self.cbStartYear.setText(_translate("nbn", "Filter out records before start year", None))
        self.sbEndYear.setToolTip(_translate("nbn", "Specify end year", None))
        self.cbEndYear.setToolTip(_translate("nbn", "<html><head/><body><p>Check box to filter out records after given end year.</p></body></html>", None))
        self.cbEndYear.setText(_translate("nbn", "Filter out records after end year", None))
        self.groupBox_2.setTitle(_translate("nbn", "Presence or absence", None))
        self.rbPresence.setToolTip(_translate("nbn", "<html><head/><body><p>If selected (the default) then only presence records are retrieved.</p></body></html>", None))
        self.rbPresence.setText(_translate("nbn", "Presence", None))
        self.rbAbsence.setToolTip(_translate("nbn", "<html><head/><body><p>If selected then only absence records are retrieved.</p></body></html>", None))
        self.rbAbsence.setText(_translate("nbn", "Absence", None))
        self.groupBox_6.setTitle(_translate("nbn", "Grid reference filter", None))
        self.leGridRef.setToolTip(_translate("nbn", "<html><head/><body><p>Specify a grid reference to use as a filter when downloading records from the NBN Gateway, or for use with the point and radius buffer creation.</p></body></html>", None))
        self.groupBox_8.setTitle(_translate("nbn", "Point and buffer tool", None))
        self.rbGR.setText(_translate("nbn", "Use grid reference", None))
        self.rbEN.setText(_translate("nbn", "Use easting/northing", None))
        self.label_7.setText(_translate("nbn", "Grid ref:", None))
        self.lePointBufferGR.setToolTip(_translate("nbn", "<html><head/><body><p>Specify a grid reference to use as a filter when downloading records from the NBN Gateway, or for use with the point and radius buffer creation.</p></body></html>", None))
        self.label_10.setText(_translate("nbn", "Easting:", None))
        self.sbEasting.setToolTip(_translate("nbn", "<html><head/><body><p>Specify an easting for use with the point and buffer convenience tool.</p></body></html>", None))
        self.label_8.setText(_translate("nbn", "Northing:", None))
        self.sbNorthing.setToolTip(_translate("nbn", "<html><head/><body><p>Specify a northing for use with the point and buffer convenience tool.</p></body></html>", None))
        self.label_9.setText(_translate("nbn", "Buffer (m):", None))
        self.sbBuffer.setToolTip(_translate("nbn", "<html><head/><body><p>Specify buffer radius in metres for use with the point and buffer convenience tool. Minimum of 10 metres and maximum of 10,000 m (10 km).</p></body></html>", None))
        self.pbBuffer.setToolTip(_translate("nbn", "<html><head/><body><p>Generate circular buffer around specified point.</p></body></html>", None))
        self.pbClearLastBuffer.setToolTip(_translate("nbn", "Remove last buffer", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_13), _translate("nbn", "Other", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("nbn", "Filters", None))
        self.lwDownloaded.setToolTip(_translate("nbn", "<html><head/><body><p>Indicates the NBN downloads performed during this session. A download icon is displayed whilst data is being downloaded from the NBN. An egg-timer icon is displayed whilst data is being reformatted and saved as a CSV file. A green tick icon shows when a CSV file has been successfully created. A red cross icon shows if there was a problem.</p></body></html>", None))
        self.pbSendToBiorec.setToolTip(_translate("nbn", "<html><head/><body><p>Send selected CSV to Biorec tool</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("nbn", "Downloads", None))

