# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_nbn.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_nbn(object):
    def setupUi(self, nbn):
        nbn.setObjectName("nbn")
        nbn.resize(407, 560)
        nbn.setStyleSheet("#pbAttention{\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 12px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"#pbAttention:pressed {\n"
"    background-color: rgb(224, 0, 0);\n"
"    border-style: inset;\n"
"}")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(nbn)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(nbn)
        self.tabWidget.setMinimumSize(QtCore.QSize(280, 230))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabOptions = QtWidgets.QWidget()
        self.tabOptions.setObjectName("tabOptions")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tabOptions)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbSpeciesWMS = QtWidgets.QPushButton(self.groupBox_3)
        self.pbSpeciesWMS.setMinimumSize(QtCore.QSize(95, 25))
        self.pbSpeciesWMS.setMaximumSize(QtCore.QSize(95, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/nbngridmap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSpeciesWMS.setIcon(icon)
        self.pbSpeciesWMS.setIconSize(QtCore.QSize(20, 20))
        self.pbSpeciesWMS.setObjectName("pbSpeciesWMS")
        self.horizontalLayout_3.addWidget(self.pbSpeciesWMS)
        self.cbGridSize = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.cbGridSize.sizePolicy().hasHeightForWidth())
        self.cbGridSize.setSizePolicy(sizePolicy)
        self.cbGridSize.setMinimumSize(QtCore.QSize(95, 25))
        self.cbGridSize.setMaximumSize(QtCore.QSize(95, 25))
        self.cbGridSize.setObjectName("cbGridSize")
        self.cbGridSize.addItem("")
        self.cbGridSize.addItem("")
        self.horizontalLayout_3.addWidget(self.cbGridSize)
        spacerItem = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.mgbWMSStyles = QgsCollapsibleGroupBox(self.tabOptions)
        self.mgbWMSStyles.setObjectName("mgbWMSStyles")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mgbWMSStyles)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.mgbWMSStyles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.mcbWMSColour = QgsColorButtonV2(self.mgbWMSStyles)
        self.mcbWMSColour.setProperty("color", QtGui.QColor(170, 0, 0))
        self.mcbWMSColour.setProperty("defaultColor", QtGui.QColor(170, 0, 0))
        self.mcbWMSColour.setProperty("showNoColor", False)
        self.mcbWMSColour.setObjectName("mcbWMSColour")
        self.horizontalLayout_11.addWidget(self.mcbWMSColour)
        self.label_2 = QtWidgets.QLabel(self.mgbWMSStyles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.sbPointSize = QtWidgets.QSpinBox(self.mgbWMSStyles)
        self.sbPointSize.setMinimum(1)
        self.sbPointSize.setMaximum(20)
        self.sbPointSize.setProperty("value", 6)
        self.sbPointSize.setObjectName("sbPointSize")
        self.horizontalLayout_11.addWidget(self.sbPointSize)
        spacerItem1 = QtWidgets.QSpacerItem(13, 16, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label = QtWidgets.QLabel(self.mgbWMSStyles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_13.addWidget(self.label)
        self.hsTransparency = QtWidgets.QSlider(self.mgbWMSStyles)
        self.hsTransparency.setProperty("value", 0)
        self.hsTransparency.setOrientation(QtCore.Qt.Horizontal)
        self.hsTransparency.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hsTransparency.setTickInterval(10)
        self.hsTransparency.setObjectName("hsTransparency")
        self.horizontalLayout_13.addWidget(self.hsTransparency)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbOutline = QtWidgets.QCheckBox(self.mgbWMSStyles)
        self.cbOutline.setObjectName("cbOutline")
        self.horizontalLayout_5.addWidget(self.cbOutline)
        self.cbGridLabels = QtWidgets.QCheckBox(self.mgbWMSStyles)
        self.cbGridLabels.setObjectName("cbGridLabels")
        self.horizontalLayout_5.addWidget(self.cbGridLabels)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addWidget(self.mgbWMSStyles)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabOptions)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pbDownload = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbDownload.sizePolicy().hasHeightForWidth())
        self.pbDownload.setSizePolicy(sizePolicy)
        self.pbDownload.setMinimumSize(QtCore.QSize(100, 25))
        self.pbDownload.setMaximumSize(QtCore.QSize(90, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/nbndownload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbDownload.setIcon(icon1)
        self.pbDownload.setIconSize(QtCore.QSize(20, 20))
        self.pbDownload.setObjectName("pbDownload")
        self.horizontalLayout_14.addWidget(self.pbDownload)
        spacerItem3 = QtWidgets.QSpacerItem(96, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabOptions)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cbIndTaxon = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbIndTaxon.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndTaxon.sizePolicy().hasHeightForWidth())
        self.cbIndTaxon.setSizePolicy(sizePolicy)
        self.cbIndTaxon.setMinimumSize(QtCore.QSize(70, 0))
        self.cbIndTaxon.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbIndTaxon.setObjectName("cbIndTaxon")
        self.horizontalLayout_8.addWidget(self.cbIndTaxon)
        self.cbIndDataset = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbIndDataset.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndDataset.sizePolicy().hasHeightForWidth())
        self.cbIndDataset.setSizePolicy(sizePolicy)
        self.cbIndDataset.setMinimumSize(QtCore.QSize(70, 0))
        self.cbIndDataset.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbIndDataset.setObjectName("cbIndDataset")
        self.horizontalLayout_8.addWidget(self.cbIndDataset)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cbIndStartYear = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbIndStartYear.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndStartYear.sizePolicy().hasHeightForWidth())
        self.cbIndStartYear.setSizePolicy(sizePolicy)
        self.cbIndStartYear.setMinimumSize(QtCore.QSize(80, 0))
        self.cbIndStartYear.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cbIndStartYear.setObjectName("cbIndStartYear")
        self.horizontalLayout_12.addWidget(self.cbIndStartYear)
        self.cbIndEndYear = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbIndEndYear.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndEndYear.sizePolicy().hasHeightForWidth())
        self.cbIndEndYear.setSizePolicy(sizePolicy)
        self.cbIndEndYear.setMinimumSize(QtCore.QSize(80, 0))
        self.cbIndEndYear.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cbIndEndYear.setObjectName("cbIndEndYear")
        self.horizontalLayout_12.addWidget(self.cbIndEndYear)
        self.cbIndPolygon = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbIndPolygon.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndPolygon.sizePolicy().hasHeightForWidth())
        self.cbIndPolygon.setSizePolicy(sizePolicy)
        self.cbIndPolygon.setMinimumSize(QtCore.QSize(70, 0))
        self.cbIndPolygon.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbIndPolygon.setObjectName("cbIndPolygon")
        self.horizontalLayout_12.addWidget(self.cbIndPolygon)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.verticalLayout_8.addWidget(self.groupBox_7)
        spacerItem6 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.butClearLast = QtWidgets.QPushButton(self.tabOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butClearLast.sizePolicy().hasHeightForWidth())
        self.butClearLast.setSizePolicy(sizePolicy)
        self.butClearLast.setMinimumSize(QtCore.QSize(30, 30))
        self.butClearLast.setMaximumSize(QtCore.QSize(30, 30))
        self.butClearLast.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/removelayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butClearLast.setIcon(icon2)
        self.butClearLast.setIconSize(QtCore.QSize(28, 28))
        self.butClearLast.setObjectName("butClearLast")
        self.horizontalLayout_2.addWidget(self.butClearLast)
        self.butClear = QtWidgets.QPushButton(self.tabOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butClear.sizePolicy().hasHeightForWidth())
        self.butClear.setSizePolicy(sizePolicy)
        self.butClear.setMinimumSize(QtCore.QSize(30, 30))
        self.butClear.setMaximumSize(QtCore.QSize(30, 30))
        self.butClear.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/removelayers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butClear.setIcon(icon3)
        self.butClear.setIconSize(QtCore.QSize(28, 28))
        self.butClear.setObjectName("butClear")
        self.horizontalLayout_2.addWidget(self.butClear)
        self.butHelp = QtWidgets.QPushButton(self.tabOptions)
        self.butHelp.setMinimumSize(QtCore.QSize(30, 30))
        self.butHelp.setMaximumSize(QtCore.QSize(30, 30))
        self.butHelp.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/bang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butHelp.setIcon(icon4)
        self.butHelp.setIconSize(QtCore.QSize(24, 24))
        self.butHelp.setObjectName("butHelp")
        self.horizontalLayout_2.addWidget(self.butHelp)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tabOptions, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_7)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leTaxonSearch = QtWidgets.QLineEdit(self.tab_8)
        self.leTaxonSearch.setObjectName("leTaxonSearch")
        self.horizontalLayout.addWidget(self.leTaxonSearch)
        self.butTaxonSearch = QtWidgets.QPushButton(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butTaxonSearch.sizePolicy().hasHeightForWidth())
        self.butTaxonSearch.setSizePolicy(sizePolicy)
        self.butTaxonSearch.setMinimumSize(QtCore.QSize(30, 30))
        self.butTaxonSearch.setMaximumSize(QtCore.QSize(30, 30))
        self.butTaxonSearch.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/speciesinventory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butTaxonSearch.setIcon(icon5)
        self.butTaxonSearch.setIconSize(QtCore.QSize(26, 26))
        self.butTaxonSearch.setObjectName("butTaxonSearch")
        self.horizontalLayout.addWidget(self.butTaxonSearch)
        self.verticalLayout_19.addLayout(self.horizontalLayout)
        self.twTaxa = QtWidgets.QTreeWidget(self.tab_8)
        self.twTaxa.setIndentation(10)
        self.twTaxa.setHeaderHidden(True)
        self.twTaxa.setColumnCount(1)
        self.twTaxa.setObjectName("twTaxa")
        self.twTaxa.headerItem().setText(0, "1")
        self.twTaxa.header().setVisible(False)
        self.twTaxa.header().setStretchLastSection(True)
        self.verticalLayout_19.addWidget(self.twTaxa)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.twProviders = QtWidgets.QTreeWidget(self.tab_9)
        self.twProviders.setHeaderHidden(True)
        self.twProviders.setColumnCount(1)
        self.twProviders.setObjectName("twProviders")
        self.twProviders.headerItem().setText(0, "1")
        self.twProviders.header().setVisible(False)
        self.twProviders.header().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.twProviders)
        self.lblDatasetFilter = QtWidgets.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblDatasetFilter.setFont(font)
        self.lblDatasetFilter.setAutoFillBackground(False)
        self.lblDatasetFilter.setWordWrap(True)
        self.lblDatasetFilter.setObjectName("lblDatasetFilter")
        self.verticalLayout_3.addWidget(self.lblDatasetFilter)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.pbUncheckAll = QtWidgets.QPushButton(self.tab_9)
        self.pbUncheckAll.setMinimumSize(QtCore.QSize(0, 0))
        self.pbUncheckAll.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pbUncheckAll.setObjectName("pbUncheckAll")
        self.horizontalLayout_9.addWidget(self.pbUncheckAll)
        self.pbRefreshDatasets = QtWidgets.QPushButton(self.tab_9)
        self.pbRefreshDatasets.setObjectName("pbRefreshDatasets")
        self.horizontalLayout_9.addWidget(self.pbRefreshDatasets)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sbStartYear = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbStartYear.sizePolicy().hasHeightForWidth())
        self.sbStartYear.setSizePolicy(sizePolicy)
        self.sbStartYear.setMinimumSize(QtCore.QSize(60, 0))
        self.sbStartYear.setMinimum(1600)
        self.sbStartYear.setMaximum(2100)
        self.sbStartYear.setSingleStep(1)
        self.sbStartYear.setProperty("value", 2000)
        self.sbStartYear.setObjectName("sbStartYear")
        self.horizontalLayout_6.addWidget(self.sbStartYear)
        self.cbStartYear = QtWidgets.QCheckBox(self.groupBox)
        self.cbStartYear.setObjectName("cbStartYear")
        self.horizontalLayout_6.addWidget(self.cbStartYear)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sbEndYear = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbEndYear.sizePolicy().hasHeightForWidth())
        self.sbEndYear.setSizePolicy(sizePolicy)
        self.sbEndYear.setMinimumSize(QtCore.QSize(60, 0))
        self.sbEndYear.setMinimum(1600)
        self.sbEndYear.setMaximum(2100)
        self.sbEndYear.setSingleStep(1)
        self.sbEndYear.setProperty("value", 2000)
        self.sbEndYear.setObjectName("sbEndYear")
        self.horizontalLayout_7.addWidget(self.sbEndYear)
        self.cbEndYear = QtWidgets.QCheckBox(self.groupBox)
        self.cbEndYear.setObjectName("cbEndYear")
        self.horizontalLayout_7.addWidget(self.cbEndYear)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addWidget(self.groupBox)
        spacerItem9 = QtWidgets.QSpacerItem(17, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.tabWidget_2.addTab(self.tab_13, "")
        self.tabUtilities = QtWidgets.QWidget()
        self.tabUtilities.setObjectName("tabUtilities")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabUtilities)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tabUtilities)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.rbGR = QtWidgets.QRadioButton(self.groupBox_8)
        self.rbGR.setChecked(True)
        self.rbGR.setObjectName("rbGR")
        self.horizontalLayout_24.addWidget(self.rbGR)
        self.rbEN = QtWidgets.QRadioButton(self.groupBox_8)
        self.rbEN.setObjectName("rbEN")
        self.horizontalLayout_24.addWidget(self.rbEN)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lePointBufferGR = QtWidgets.QLineEdit(self.groupBox_8)
        self.lePointBufferGR.setObjectName("lePointBufferGR")
        self.horizontalLayout_4.addWidget(self.lePointBufferGR)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.sbEasting = QtWidgets.QSpinBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbEasting.sizePolicy().hasHeightForWidth())
        self.sbEasting.setSizePolicy(sizePolicy)
        self.sbEasting.setMinimumSize(QtCore.QSize(60, 0))
        self.sbEasting.setMinimum(0)
        self.sbEasting.setMaximum(2000000)
        self.sbEasting.setSingleStep(1000)
        self.sbEasting.setProperty("value", 0)
        self.sbEasting.setObjectName("sbEasting")
        self.horizontalLayout_10.addWidget(self.sbEasting)
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.sbNorthing = QtWidgets.QSpinBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbNorthing.sizePolicy().hasHeightForWidth())
        self.sbNorthing.setSizePolicy(sizePolicy)
        self.sbNorthing.setMinimumSize(QtCore.QSize(60, 0))
        self.sbNorthing.setMinimum(0)
        self.sbNorthing.setMaximum(2000000)
        self.sbNorthing.setSingleStep(1000)
        self.sbNorthing.setProperty("value", 0)
        self.sbNorthing.setObjectName("sbNorthing")
        self.horizontalLayout_10.addWidget(self.sbNorthing)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_22.addWidget(self.label_9)
        self.sbBuffer = QtWidgets.QSpinBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbBuffer.sizePolicy().hasHeightForWidth())
        self.sbBuffer.setSizePolicy(sizePolicy)
        self.sbBuffer.setMinimumSize(QtCore.QSize(60, 0))
        self.sbBuffer.setMinimum(10)
        self.sbBuffer.setMaximum(10000)
        self.sbBuffer.setSingleStep(10)
        self.sbBuffer.setProperty("value", 2000)
        self.sbBuffer.setObjectName("sbBuffer")
        self.horizontalLayout_22.addWidget(self.sbBuffer)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem11)
        self.pbBuffer = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbBuffer.sizePolicy().hasHeightForWidth())
        self.pbBuffer.setSizePolicy(sizePolicy)
        self.pbBuffer.setMinimumSize(QtCore.QSize(30, 30))
        self.pbBuffer.setMaximumSize(QtCore.QSize(30, 30))
        self.pbBuffer.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/buffer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbBuffer.setIcon(icon6)
        self.pbBuffer.setIconSize(QtCore.QSize(26, 26))
        self.pbBuffer.setObjectName("pbBuffer")
        self.horizontalLayout_22.addWidget(self.pbBuffer)
        self.pbClearLastBuffer = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClearLastBuffer.sizePolicy().hasHeightForWidth())
        self.pbClearLastBuffer.setSizePolicy(sizePolicy)
        self.pbClearLastBuffer.setMinimumSize(QtCore.QSize(30, 30))
        self.pbClearLastBuffer.setMaximumSize(QtCore.QSize(30, 30))
        self.pbClearLastBuffer.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/bufferclear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClearLastBuffer.setIcon(icon7)
        self.pbClearLastBuffer.setIconSize(QtCore.QSize(26, 26))
        self.pbClearLastBuffer.setObjectName("pbClearLastBuffer")
        self.horizontalLayout_22.addWidget(self.pbClearLastBuffer)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        spacerItem12 = QtWidgets.QSpacerItem(20, 285, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.tabWidget_2.addTab(self.tabUtilities, "")
        self.verticalLayout_11.addWidget(self.tabWidget_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem13)
        self.pbClearFilters = QtWidgets.QPushButton(self.tab_7)
        self.pbClearFilters.setObjectName("pbClearFilters")
        self.horizontalLayout_15.addWidget(self.pbClearFilters)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lwDownloaded = QtWidgets.QListWidget(self.tab_4)
        self.lwDownloaded.setObjectName("lwDownloaded")
        self.verticalLayout_10.addWidget(self.lwDownloaded)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem14)
        self.pbSendToBiorec = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSendToBiorec.sizePolicy().hasHeightForWidth())
        self.pbSendToBiorec.setSizePolicy(sizePolicy)
        self.pbSendToBiorec.setMinimumSize(QtCore.QSize(32, 32))
        self.pbSendToBiorec.setMaximumSize(QtCore.QSize(32, 32))
        self.pbSendToBiorec.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/maptaxa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSendToBiorec.setIcon(icon8)
        self.pbSendToBiorec.setIconSize(QtCore.QSize(30, 30))
        self.pbSendToBiorec.setObjectName("pbSendToBiorec")
        self.horizontalLayout_16.addWidget(self.pbSendToBiorec)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_9.addWidget(self.tabWidget)

        self.retranslateUi(nbn)
        self.tabWidget.setCurrentIndex(0)
        self.cbGridSize.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(nbn)

    def retranslateUi(self, nbn):
        _translate = QtCore.QCoreApplication.translate
        nbn.setWindowTitle(_translate("nbn", "TomBio"))
        self.groupBox_3.setTitle(_translate("nbn", "NBN Atlas Map (WMS)"))
        self.pbSpeciesWMS.setToolTip(_translate("nbn", "<html><head/><body><p>Fetch species distribution map from NBN Atlas WMS.</p></body></html>"))
        self.pbSpeciesWMS.setText(_translate("nbn", "Map"))
        self.cbGridSize.setToolTip(_translate("nbn", "<html><head/><body><p>Points for each record or grid squares?</p></body></html>"))
        self.cbGridSize.setItemText(0, _translate("nbn", "Record points"))
        self.cbGridSize.setItemText(1, _translate("nbn", "Atlas squares"))
        self.mgbWMSStyles.setTitle(_translate("nbn", "WMS styling"))
        self.label_3.setText(_translate("nbn", "Colour:"))
        self.mcbWMSColour.setToolTip(_translate("nbn", "Select the colour to use for the records/squares"))
        self.mcbWMSColour.setProperty("colorDialogTitle", _translate("nbn", "Select colour  for WMS points or grid"))
        self.label_2.setText(_translate("nbn", "Point size:"))
        self.sbPointSize.setToolTip(_translate("nbn", "Indicate the size of record points"))
        self.label.setText(_translate("nbn", "Transparency:"))
        self.hsTransparency.setToolTip(_translate("nbn", "Set transparency of layer to be created"))
        self.cbOutline.setToolTip(_translate("nbn", "Indicate whether or not you want points or squares to be outlined."))
        self.cbOutline.setText(_translate("nbn", "Outline"))
        self.cbGridLabels.setToolTip(_translate("nbn", "Indicate whether or not you want squares to be labelled with their grid reference."))
        self.cbGridLabels.setText(_translate("nbn", "Grid square labels"))
        self.groupBox_5.setTitle(_translate("nbn", "NBN Atlas Records Download"))
        self.pbDownload.setToolTip(_translate("nbn", "<html><head/><body><p>Download observation records from the NBN Atlas. You must specify at least one of the following filters: taxon, dataset (or data provider) or polygon.</p></body></html>"))
        self.pbDownload.setText(_translate("nbn", "Download   "))
        self.groupBox_7.setTitle(_translate("nbn", "Specified Filters"))
        self.cbIndTaxon.setText(_translate("nbn", "Species"))
        self.cbIndDataset.setText(_translate("nbn", "Dataset"))
        self.cbIndStartYear.setText(_translate("nbn", "Start year"))
        self.cbIndEndYear.setText(_translate("nbn", "End year"))
        self.cbIndPolygon.setText(_translate("nbn", "Polygon"))
        self.butClearLast.setToolTip(_translate("nbn", "Remove last NBN Atlas WMS layer"))
        self.butClear.setToolTip(_translate("nbn", "Remove all NBN Atlas WMS layers"))
        self.butHelp.setToolTip(_translate("nbn", "Tips and help for this tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOptions), _translate("nbn", "NBN"))
        self.leTaxonSearch.setToolTip(_translate("nbn", "Enter search term for taxon"))
        self.butTaxonSearch.setToolTip(_translate("nbn", "Search the UK Species Inventory"))
        self.twTaxa.setToolTip(_translate("nbn", "<html><head/><body><p>Matching taxa - check the species you want.</p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("nbn", "Taxon"))
        self.twProviders.setToolTip(_translate("nbn", "<html><head/><body><p>NBN Datasets - check to filter</p></body></html>"))
        self.lblDatasetFilter.setText(_translate("nbn", "lblDatasetFilter"))
        self.pbUncheckAll.setToolTip(_translate("nbn", "Uncheck all dataset items"))
        self.pbUncheckAll.setText(_translate("nbn", "Clear dataset filters"))
        self.pbRefreshDatasets.setToolTip(_translate("nbn", "<html><head/><body><p>Update the dataset list from the NBN Atlas</p></body></html>"))
        self.pbRefreshDatasets.setText(_translate("nbn", "Refresh list"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("nbn", "Dataset"))
        self.groupBox.setTitle(_translate("nbn", "Year"))
        self.sbStartYear.setToolTip(_translate("nbn", "Specify start year"))
        self.cbStartYear.setToolTip(_translate("nbn", "<html><head/><body><p>Check box to filter out records before given start year.</p></body></html>"))
        self.cbStartYear.setText(_translate("nbn", "Filter out records before start year"))
        self.sbEndYear.setToolTip(_translate("nbn", "Specify end year"))
        self.cbEndYear.setToolTip(_translate("nbn", "<html><head/><body><p>Check box to filter out records after given end year.</p></body></html>"))
        self.cbEndYear.setText(_translate("nbn", "Filter out records after end year"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_13), _translate("nbn", "Dates"))
        self.groupBox_8.setTitle(_translate("nbn", "Point and buffer tool"))
        self.rbGR.setText(_translate("nbn", "Use grid reference"))
        self.rbEN.setText(_translate("nbn", "Use easting/northing"))
        self.label_7.setText(_translate("nbn", "Grid ref:"))
        self.lePointBufferGR.setToolTip(_translate("nbn", "<html><head/><body><p>Specify a grid reference to use as a filter when downloading records from the NBN Gateway, or for use with the point and radius buffer creation.</p></body></html>"))
        self.label_10.setText(_translate("nbn", "Easting:"))
        self.sbEasting.setToolTip(_translate("nbn", "<html><head/><body><p>Specify an easting for use with the point and buffer convenience tool.</p></body></html>"))
        self.label_8.setText(_translate("nbn", "Northing:"))
        self.sbNorthing.setToolTip(_translate("nbn", "<html><head/><body><p>Specify a northing for use with the point and buffer convenience tool.</p></body></html>"))
        self.label_9.setText(_translate("nbn", "Buffer (m):"))
        self.sbBuffer.setToolTip(_translate("nbn", "<html><head/><body><p>Specify buffer radius in metres for use with the point and buffer convenience tool. Minimum of 10 metres and maximum of 10,000 m (10 km).</p></body></html>"))
        self.pbBuffer.setToolTip(_translate("nbn", "<html><head/><body><p>Generate circular buffer around specified point.</p></body></html>"))
        self.pbClearLastBuffer.setToolTip(_translate("nbn", "Remove last buffer"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabUtilities), _translate("nbn", "Utilities"))
        self.pbClearFilters.setToolTip(_translate("nbn", "Clear all filters"))
        self.pbClearFilters.setText(_translate("nbn", "Clear all filters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("nbn", "Filters"))
        self.lwDownloaded.setToolTip(_translate("nbn", "<html><head/><body><p>Indicates the NBN downloads performed during this session. A download icon is displayed whilst data is being downloaded from the NBN. An egg-timer icon is displayed whilst data is being reformatted and saved as a CSV file. A green tick icon shows when a CSV file has been successfully created. A red cross icon shows if there was a problem.</p></body></html>"))
        self.pbSendToBiorec.setToolTip(_translate("nbn", "<html><head/><body><p>Send selected CSV to Biorec tool</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("nbn", "Downloads"))

from qgis.gui import QgsColorButtonV2
from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
