# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_nbn.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_nbn(object):
    def setupUi(self, nbn):
        nbn.setObjectName("nbn")
        nbn.resize(351, 481)
        nbn.setStyleSheet("#pbAttention{\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 12px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"#pbAttention:pressed {\n"
"    background-color: rgb(224, 0, 0);\n"
"    border-style: inset;\n"
"}")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(nbn)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(nbn)
        self.tabWidget.setMinimumSize(QtCore.QSize(280, 230))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabOptions = QtWidgets.QWidget()
        self.tabOptions.setObjectName("tabOptions")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tabOptions)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbSpeciesWMS = QtWidgets.QPushButton(self.groupBox_3)
        self.pbSpeciesWMS.setMinimumSize(QtCore.QSize(95, 25))
        self.pbSpeciesWMS.setMaximumSize(QtCore.QSize(95, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/nbngridmap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbSpeciesWMS.setIcon(icon)
        self.pbSpeciesWMS.setIconSize(QtCore.QSize(20, 20))
        self.pbSpeciesWMS.setObjectName("pbSpeciesWMS")
        self.horizontalLayout_3.addWidget(self.pbSpeciesWMS)
        self.cbGridSize = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbGridSize.sizePolicy().hasHeightForWidth())
        self.cbGridSize.setSizePolicy(sizePolicy)
        self.cbGridSize.setMinimumSize(QtCore.QSize(95, 23))
        self.cbGridSize.setMaximumSize(QtCore.QSize(95, 23))
        self.cbGridSize.setObjectName("cbGridSize")
        self.cbGridSize.addItem("")
        self.cbGridSize.addItem("")
        self.horizontalLayout_3.addWidget(self.cbGridSize)
        spacerItem = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_12.addWidget(self.groupBox_3)
        self.mgbWMSStyles = QgsCollapsibleGroupBox(self.tabOptions)
        self.mgbWMSStyles.setObjectName("mgbWMSStyles")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mgbWMSStyles)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.mgbWMSStyles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.mcbWMSColour = QgsColorButton(self.mgbWMSStyles)
        self.mcbWMSColour.setMinimumSize(QtCore.QSize(0, 0))
        self.mcbWMSColour.setAcceptDrops(False)
        self.mcbWMSColour.setIconSize(QtCore.QSize(98, 16))
        self.mcbWMSColour.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.mcbWMSColour.setColor(QtGui.QColor(170, 0, 0))
        self.mcbWMSColour.setDefaultColor(QtGui.QColor(170, 0, 0))
        self.mcbWMSColour.setObjectName("mcbWMSColour")
        self.horizontalLayout_11.addWidget(self.mcbWMSColour)
        self.label_2 = QtWidgets.QLabel(self.mgbWMSStyles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.sbPointSize = QtWidgets.QSpinBox(self.mgbWMSStyles)
        self.sbPointSize.setMinimum(1)
        self.sbPointSize.setMaximum(20)
        self.sbPointSize.setProperty("value", 6)
        self.sbPointSize.setObjectName("sbPointSize")
        self.horizontalLayout_11.addWidget(self.sbPointSize)
        spacerItem1 = QtWidgets.QSpacerItem(13, 16, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label = QtWidgets.QLabel(self.mgbWMSStyles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_13.addWidget(self.label)
        self.hsTransparency = QtWidgets.QSlider(self.mgbWMSStyles)
        self.hsTransparency.setProperty("value", 0)
        self.hsTransparency.setOrientation(QtCore.Qt.Horizontal)
        self.hsTransparency.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hsTransparency.setTickInterval(10)
        self.hsTransparency.setObjectName("hsTransparency")
        self.horizontalLayout_13.addWidget(self.hsTransparency)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbOutline = QtWidgets.QCheckBox(self.mgbWMSStyles)
        self.cbOutline.setObjectName("cbOutline")
        self.horizontalLayout_5.addWidget(self.cbOutline)
        self.cbGridLabels = QtWidgets.QCheckBox(self.mgbWMSStyles)
        self.cbGridLabels.setObjectName("cbGridLabels")
        self.horizontalLayout_5.addWidget(self.cbGridLabels)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_12.addWidget(self.mgbWMSStyles)
        self.mGroupBox = QgsCollapsibleGroupBox(self.tabOptions)
        self.mGroupBox.setObjectName("mGroupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.mGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pbDownload = QtWidgets.QPushButton(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbDownload.sizePolicy().hasHeightForWidth())
        self.pbDownload.setSizePolicy(sizePolicy)
        self.pbDownload.setMinimumSize(QtCore.QSize(100, 25))
        self.pbDownload.setMaximumSize(QtCore.QSize(90, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/nbndownload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbDownload.setIcon(icon1)
        self.pbDownload.setIconSize(QtCore.QSize(20, 20))
        self.pbDownload.setObjectName("pbDownload")
        self.horizontalLayout_17.addWidget(self.pbDownload)
        self.cboDownloadReason = QtWidgets.QComboBox(self.mGroupBox)
        self.cboDownloadReason.setMinimumSize(QtCore.QSize(0, 23))
        self.cboDownloadReason.setMaximumSize(QtCore.QSize(16777215, 23))
        self.cboDownloadReason.setObjectName("cboDownloadReason")
        self.horizontalLayout_17.addWidget(self.cboDownloadReason)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.leNbnOutputFolder = QtWidgets.QLineEdit(self.mGroupBox)
        self.leNbnOutputFolder.setObjectName("leNbnOutputFolder")
        self.horizontalLayout_14.addWidget(self.leNbnOutputFolder)
        self.pbBrowseNbnOutputFolder = QtWidgets.QPushButton(self.mGroupBox)
        self.pbBrowseNbnOutputFolder.setObjectName("pbBrowseNbnOutputFolder")
        self.horizontalLayout_14.addWidget(self.pbBrowseNbnOutputFolder)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.verticalLayout_12.addWidget(self.mGroupBox)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabOptions)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cbIndTaxon = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbIndTaxon.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndTaxon.sizePolicy().hasHeightForWidth())
        self.cbIndTaxon.setSizePolicy(sizePolicy)
        self.cbIndTaxon.setMinimumSize(QtCore.QSize(70, 0))
        self.cbIndTaxon.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbIndTaxon.setObjectName("cbIndTaxon")
        self.horizontalLayout_8.addWidget(self.cbIndTaxon)
        self.cbIndDataset = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbIndDataset.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndDataset.sizePolicy().hasHeightForWidth())
        self.cbIndDataset.setSizePolicy(sizePolicy)
        self.cbIndDataset.setMinimumSize(QtCore.QSize(70, 0))
        self.cbIndDataset.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbIndDataset.setObjectName("cbIndDataset")
        self.horizontalLayout_8.addWidget(self.cbIndDataset)
        self.cbIndSpeciesList = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbIndSpeciesList.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndSpeciesList.sizePolicy().hasHeightForWidth())
        self.cbIndSpeciesList.setSizePolicy(sizePolicy)
        self.cbIndSpeciesList.setMinimumSize(QtCore.QSize(70, 0))
        self.cbIndSpeciesList.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbIndSpeciesList.setObjectName("cbIndSpeciesList")
        self.horizontalLayout_8.addWidget(self.cbIndSpeciesList)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cbIndStartYear = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbIndStartYear.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndStartYear.sizePolicy().hasHeightForWidth())
        self.cbIndStartYear.setSizePolicy(sizePolicy)
        self.cbIndStartYear.setMinimumSize(QtCore.QSize(80, 0))
        self.cbIndStartYear.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cbIndStartYear.setObjectName("cbIndStartYear")
        self.horizontalLayout_12.addWidget(self.cbIndStartYear)
        self.cbIndEndYear = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbIndEndYear.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndEndYear.sizePolicy().hasHeightForWidth())
        self.cbIndEndYear.setSizePolicy(sizePolicy)
        self.cbIndEndYear.setMinimumSize(QtCore.QSize(80, 0))
        self.cbIndEndYear.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cbIndEndYear.setObjectName("cbIndEndYear")
        self.horizontalLayout_12.addWidget(self.cbIndEndYear)
        self.cbIndPolygon = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbIndPolygon.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndPolygon.sizePolicy().hasHeightForWidth())
        self.cbIndPolygon.setSizePolicy(sizePolicy)
        self.cbIndPolygon.setMinimumSize(QtCore.QSize(70, 0))
        self.cbIndPolygon.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cbIndPolygon.setObjectName("cbIndPolygon")
        self.horizontalLayout_12.addWidget(self.cbIndPolygon)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.verticalLayout_12.addWidget(self.groupBox_7)
        spacerItem5 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem5)
        self.tabWidget.addTab(self.tabOptions, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabFilters = QtWidgets.QTabWidget(self.tab_7)
        self.tabFilters.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabFilters.setObjectName("tabFilters")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leTaxonSearch = QtWidgets.QLineEdit(self.tab_8)
        self.leTaxonSearch.setObjectName("leTaxonSearch")
        self.horizontalLayout.addWidget(self.leTaxonSearch)
        self.butTaxonSearch = QtWidgets.QPushButton(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butTaxonSearch.sizePolicy().hasHeightForWidth())
        self.butTaxonSearch.setSizePolicy(sizePolicy)
        self.butTaxonSearch.setMinimumSize(QtCore.QSize(30, 30))
        self.butTaxonSearch.setMaximumSize(QtCore.QSize(30, 30))
        self.butTaxonSearch.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/speciesinventory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butTaxonSearch.setIcon(icon2)
        self.butTaxonSearch.setIconSize(QtCore.QSize(26, 26))
        self.butTaxonSearch.setObjectName("butTaxonSearch")
        self.horizontalLayout.addWidget(self.butTaxonSearch)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.tab_8)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.twTaxa = QtWidgets.QTreeWidget(self.splitter)
        self.twTaxa.setIndentation(10)
        self.twTaxa.setHeaderHidden(True)
        self.twTaxa.setColumnCount(1)
        self.twTaxa.setObjectName("twTaxa")
        self.twTaxa.headerItem().setText(0, "1")
        self.twTaxa.header().setVisible(False)
        self.twTaxa.header().setStretchLastSection(True)
        self.lwTaxa = QtWidgets.QListWidget(self.splitter)
        self.lwTaxa.setObjectName("lwTaxa")
        self.verticalLayout_15.addWidget(self.splitter)
        self.label_5 = QtWidgets.QLabel(self.tab_8)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_15.addWidget(self.label_5)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.pbClearTaxonFilters = QtWidgets.QPushButton(self.tab_8)
        self.pbClearTaxonFilters.setObjectName("pbClearTaxonFilters")
        self.horizontalLayout_16.addWidget(self.pbClearTaxonFilters)
        self.verticalLayout_15.addLayout(self.horizontalLayout_16)
        self.tabFilters.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.twProviders = QtWidgets.QTreeWidget(self.tab_9)
        self.twProviders.setHeaderHidden(True)
        self.twProviders.setColumnCount(1)
        self.twProviders.setObjectName("twProviders")
        self.twProviders.headerItem().setText(0, "1")
        self.twProviders.header().setVisible(False)
        self.twProviders.header().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.twProviders)
        self.lblDatasetFilter = QtWidgets.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblDatasetFilter.setFont(font)
        self.lblDatasetFilter.setAutoFillBackground(False)
        self.lblDatasetFilter.setWordWrap(True)
        self.lblDatasetFilter.setObjectName("lblDatasetFilter")
        self.verticalLayout_3.addWidget(self.lblDatasetFilter)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.pbUncheckAll = QtWidgets.QPushButton(self.tab_9)
        self.pbUncheckAll.setMinimumSize(QtCore.QSize(0, 0))
        self.pbUncheckAll.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pbUncheckAll.setObjectName("pbUncheckAll")
        self.horizontalLayout_9.addWidget(self.pbUncheckAll)
        self.pbRefreshDatasets = QtWidgets.QPushButton(self.tab_9)
        self.pbRefreshDatasets.setObjectName("pbRefreshDatasets")
        self.horizontalLayout_9.addWidget(self.pbRefreshDatasets)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.tabFilters.addTab(self.tab_9, "")
        self.tabSpeciesLists = QtWidgets.QWidget()
        self.tabSpeciesLists.setObjectName("tabSpeciesLists")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tabSpeciesLists)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.twSpeciesLists = QtWidgets.QTreeWidget(self.tabSpeciesLists)
        self.twSpeciesLists.setObjectName("twSpeciesLists")
        self.twSpeciesLists.headerItem().setText(0, "1")
        self.twSpeciesLists.header().setVisible(False)
        self.verticalLayout_16.addWidget(self.twSpeciesLists)
        self.lblSpeciesListFilter = QtWidgets.QLabel(self.tabSpeciesLists)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSpeciesListFilter.setFont(font)
        self.lblSpeciesListFilter.setAutoFillBackground(False)
        self.lblSpeciesListFilter.setWordWrap(True)
        self.lblSpeciesListFilter.setObjectName("lblSpeciesListFilter")
        self.verticalLayout_16.addWidget(self.lblSpeciesListFilter)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.pbUncheckAllSpeciesList = QtWidgets.QPushButton(self.tabSpeciesLists)
        self.pbUncheckAllSpeciesList.setMinimumSize(QtCore.QSize(0, 0))
        self.pbUncheckAllSpeciesList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pbUncheckAllSpeciesList.setObjectName("pbUncheckAllSpeciesList")
        self.horizontalLayout_18.addWidget(self.pbUncheckAllSpeciesList)
        self.pbRefreshSpeciesLists = QtWidgets.QPushButton(self.tabSpeciesLists)
        self.pbRefreshSpeciesLists.setObjectName("pbRefreshSpeciesLists")
        self.horizontalLayout_18.addWidget(self.pbRefreshSpeciesLists)
        self.verticalLayout_16.addLayout(self.horizontalLayout_18)
        self.tabFilters.addTab(self.tabSpeciesLists, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sbStartYear = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbStartYear.sizePolicy().hasHeightForWidth())
        self.sbStartYear.setSizePolicy(sizePolicy)
        self.sbStartYear.setMinimumSize(QtCore.QSize(60, 0))
        self.sbStartYear.setMinimum(1600)
        self.sbStartYear.setMaximum(2100)
        self.sbStartYear.setSingleStep(1)
        self.sbStartYear.setProperty("value", 2000)
        self.sbStartYear.setObjectName("sbStartYear")
        self.horizontalLayout_6.addWidget(self.sbStartYear)
        self.cbStartYear = QtWidgets.QCheckBox(self.groupBox)
        self.cbStartYear.setObjectName("cbStartYear")
        self.horizontalLayout_6.addWidget(self.cbStartYear)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sbEndYear = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbEndYear.sizePolicy().hasHeightForWidth())
        self.sbEndYear.setSizePolicy(sizePolicy)
        self.sbEndYear.setMinimumSize(QtCore.QSize(60, 0))
        self.sbEndYear.setMinimum(1600)
        self.sbEndYear.setMaximum(2100)
        self.sbEndYear.setSingleStep(1)
        self.sbEndYear.setProperty("value", 2000)
        self.sbEndYear.setObjectName("sbEndYear")
        self.horizontalLayout_7.addWidget(self.sbEndYear)
        self.cbEndYear = QtWidgets.QCheckBox(self.groupBox)
        self.cbEndYear.setObjectName("cbEndYear")
        self.horizontalLayout_7.addWidget(self.cbEndYear)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addWidget(self.groupBox)
        spacerItem9 = QtWidgets.QSpacerItem(17, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.tabFilters.addTab(self.tab_13, "")
        self.tabUtilities = QtWidgets.QWidget()
        self.tabUtilities.setObjectName("tabUtilities")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tabUtilities)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tabUtilities)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.rbGR = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbGR.setChecked(True)
        self.rbGR.setObjectName("rbGR")
        self.horizontalLayout_19.addWidget(self.rbGR)
        self.rbEN = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbEN.setObjectName("rbEN")
        self.horizontalLayout_19.addWidget(self.rbEN)
        spacerItem10 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem10)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_22.addWidget(self.label_7)
        self.lePointBufferGR = QtWidgets.QLineEdit(self.groupBox_6)
        self.lePointBufferGR.setEnabled(True)
        self.lePointBufferGR.setObjectName("lePointBufferGR")
        self.horizontalLayout_22.addWidget(self.lePointBufferGR)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.sbEasting = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbEasting.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbEasting.sizePolicy().hasHeightForWidth())
        self.sbEasting.setSizePolicy(sizePolicy)
        self.sbEasting.setMinimumSize(QtCore.QSize(40, 0))
        self.sbEasting.setMinimum(0)
        self.sbEasting.setMaximum(2000000)
        self.sbEasting.setSingleStep(1000)
        self.sbEasting.setProperty("value", 0)
        self.sbEasting.setObjectName("sbEasting")
        self.horizontalLayout_10.addWidget(self.sbEasting)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.sbNorthing = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbNorthing.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbNorthing.sizePolicy().hasHeightForWidth())
        self.sbNorthing.setSizePolicy(sizePolicy)
        self.sbNorthing.setMinimumSize(QtCore.QSize(40, 0))
        self.sbNorthing.setMinimum(0)
        self.sbNorthing.setMaximum(2000000)
        self.sbNorthing.setSingleStep(1000)
        self.sbNorthing.setProperty("value", 0)
        self.sbNorthing.setObjectName("sbNorthing")
        self.horizontalLayout_10.addWidget(self.sbNorthing)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.rbBritishEN = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbBritishEN.setEnabled(True)
        self.rbBritishEN.setChecked(True)
        self.rbBritishEN.setObjectName("rbBritishEN")
        self.horizontalLayout_20.addWidget(self.rbBritishEN)
        self.rbIrishEN = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbIrishEN.setEnabled(True)
        self.rbIrishEN.setObjectName("rbIrishEN")
        self.horizontalLayout_20.addWidget(self.rbIrishEN)
        spacerItem11 = QtWidgets.QSpacerItem(126, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_21.addWidget(self.label_9)
        self.sbBuffer = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbBuffer.sizePolicy().hasHeightForWidth())
        self.sbBuffer.setSizePolicy(sizePolicy)
        self.sbBuffer.setMinimumSize(QtCore.QSize(60, 0))
        self.sbBuffer.setMinimum(10)
        self.sbBuffer.setMaximum(10000)
        self.sbBuffer.setSingleStep(10)
        self.sbBuffer.setProperty("value", 2000)
        self.sbBuffer.setObjectName("sbBuffer")
        self.horizontalLayout_21.addWidget(self.sbBuffer)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem12)
        self.pbBuffer = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbBuffer.sizePolicy().hasHeightForWidth())
        self.pbBuffer.setSizePolicy(sizePolicy)
        self.pbBuffer.setMinimumSize(QtCore.QSize(30, 30))
        self.pbBuffer.setMaximumSize(QtCore.QSize(30, 30))
        self.pbBuffer.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/buffer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbBuffer.setIcon(icon3)
        self.pbBuffer.setIconSize(QtCore.QSize(26, 26))
        self.pbBuffer.setObjectName("pbBuffer")
        self.horizontalLayout_21.addWidget(self.pbBuffer)
        self.pbClearLastBuffer = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbClearLastBuffer.sizePolicy().hasHeightForWidth())
        self.pbClearLastBuffer.setSizePolicy(sizePolicy)
        self.pbClearLastBuffer.setMinimumSize(QtCore.QSize(30, 30))
        self.pbClearLastBuffer.setMaximumSize(QtCore.QSize(30, 30))
        self.pbClearLastBuffer.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/bufferclear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbClearLastBuffer.setIcon(icon4)
        self.pbClearLastBuffer.setIconSize(QtCore.QSize(26, 26))
        self.pbClearLastBuffer.setObjectName("pbClearLastBuffer")
        self.horizontalLayout_21.addWidget(self.pbClearLastBuffer)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.verticalLayout_17.addWidget(self.groupBox_8)
        spacerItem13 = QtWidgets.QSpacerItem(20, 285, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem13)
        self.tabFilters.addTab(self.tabUtilities, "")
        self.verticalLayout_11.addWidget(self.tabFilters)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.pbClearFilters = QtWidgets.QPushButton(self.tab_7)
        self.pbClearFilters.setObjectName("pbClearFilters")
        self.horizontalLayout_15.addWidget(self.pbClearFilters)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.tabWidget.addTab(self.tab_7, "")
        self.tabDownloads = QtWidgets.QWidget()
        self.tabDownloads.setObjectName("tabDownloads")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tabDownloads)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.tabDownloads)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.twDownloaded = QtWidgets.QTreeWidget(self.tabDownloads)
        self.twDownloaded.setObjectName("twDownloaded")
        self.twDownloaded.headerItem().setText(0, "1")
        self.twDownloaded.header().setVisible(False)
        self.verticalLayout_10.addWidget(self.twDownloaded)
        self.tabWidget.addTab(self.tabDownloads, "")
        self.tabMetadata = QtWidgets.QWidget()
        self.tabMetadata.setObjectName("tabMetadata")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tabMetadata)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.mGroupBox_2 = QgsCollapsibleGroupBox(self.tabMetadata)
        self.mGroupBox_2.setObjectName("mGroupBox_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.mGroupBox_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lblMetadata = QtWidgets.QLabel(self.mGroupBox_2)
        self.lblMetadata.setWordWrap(True)
        self.lblMetadata.setObjectName("lblMetadata")
        self.verticalLayout_13.addWidget(self.lblMetadata)
        self.cbShowAllMetadata = QtWidgets.QCheckBox(self.mGroupBox_2)
        self.cbShowAllMetadata.setObjectName("cbShowAllMetadata")
        self.verticalLayout_13.addWidget(self.cbShowAllMetadata)
        self.verticalLayout_14.addWidget(self.mGroupBox_2)
        self.twMetadata = QtWidgets.QTableWidget(self.tabMetadata)
        self.twMetadata.setObjectName("twMetadata")
        self.twMetadata.setColumnCount(0)
        self.twMetadata.setRowCount(0)
        self.twMetadata.horizontalHeader().setSortIndicatorShown(False)
        self.twMetadata.verticalHeader().setCascadingSectionResizes(True)
        self.twMetadata.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout_14.addWidget(self.twMetadata)
        self.tabWidget.addTab(self.tabMetadata, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.butClearLast = QtWidgets.QPushButton(nbn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butClearLast.sizePolicy().hasHeightForWidth())
        self.butClearLast.setSizePolicy(sizePolicy)
        self.butClearLast.setMinimumSize(QtCore.QSize(30, 30))
        self.butClearLast.setMaximumSize(QtCore.QSize(30, 30))
        self.butClearLast.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/removelayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butClearLast.setIcon(icon5)
        self.butClearLast.setIconSize(QtCore.QSize(28, 28))
        self.butClearLast.setObjectName("butClearLast")
        self.horizontalLayout_2.addWidget(self.butClearLast)
        self.butClear = QtWidgets.QPushButton(nbn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butClear.sizePolicy().hasHeightForWidth())
        self.butClear.setSizePolicy(sizePolicy)
        self.butClear.setMinimumSize(QtCore.QSize(30, 30))
        self.butClear.setMaximumSize(QtCore.QSize(30, 30))
        self.butClear.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/removelayers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butClear.setIcon(icon6)
        self.butClear.setIconSize(QtCore.QSize(28, 28))
        self.butClear.setObjectName("butClear")
        self.horizontalLayout_2.addWidget(self.butClear)
        spacerItem15 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.butHelp = QtWidgets.QPushButton(nbn)
        self.butHelp.setMinimumSize(QtCore.QSize(30, 30))
        self.butHelp.setMaximumSize(QtCore.QSize(30, 30))
        self.butHelp.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butHelp.setIcon(icon7)
        self.butHelp.setIconSize(QtCore.QSize(24, 24))
        self.butHelp.setObjectName("butHelp")
        self.horizontalLayout_2.addWidget(self.butHelp)
        self.butGithub = QtWidgets.QPushButton(nbn)
        self.butGithub.setMinimumSize(QtCore.QSize(30, 30))
        self.butGithub.setMaximumSize(QtCore.QSize(30, 30))
        self.butGithub.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butGithub.setIcon(icon8)
        self.butGithub.setIconSize(QtCore.QSize(24, 24))
        self.butGithub.setObjectName("butGithub")
        self.horizontalLayout_2.addWidget(self.butGithub)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)

        self.retranslateUi(nbn)
        self.tabWidget.setCurrentIndex(0)
        self.cbGridSize.setCurrentIndex(0)
        self.tabFilters.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(nbn)

    def retranslateUi(self, nbn):
        _translate = QtCore.QCoreApplication.translate
        nbn.setWindowTitle(_translate("nbn", "FSC QGIS plugin"))
        self.groupBox_3.setTitle(_translate("nbn", "NBN Atlas Map (WMS)"))
        self.pbSpeciesWMS.setToolTip(_translate("nbn", "<html><head/><body><p>Fetch species distribution map from NBN Atlas WMS.</p></body></html>"))
        self.pbSpeciesWMS.setText(_translate("nbn", "Map"))
        self.cbGridSize.setToolTip(_translate("nbn", "<html><head/><body><p>Points for each record or grid squares?</p></body></html>"))
        self.cbGridSize.setItemText(0, _translate("nbn", "Record points"))
        self.cbGridSize.setItemText(1, _translate("nbn", "Atlas squares"))
        self.mgbWMSStyles.setTitle(_translate("nbn", "WMS styling"))
        self.label_3.setText(_translate("nbn", "Colour:"))
        self.mcbWMSColour.setToolTip(_translate("nbn", "Select the colour to use for the records/squares"))
        self.mcbWMSColour.setColorDialogTitle(_translate("nbn", "Select colour  for WMS points or grid"))
        self.label_2.setText(_translate("nbn", "Point size:"))
        self.sbPointSize.setToolTip(_translate("nbn", "Indicate the size of record points"))
        self.label.setText(_translate("nbn", "Transparency:"))
        self.hsTransparency.setToolTip(_translate("nbn", "Set transparency of layer to be created"))
        self.cbOutline.setToolTip(_translate("nbn", "Indicate whether or not you want points or squares to be outlined."))
        self.cbOutline.setText(_translate("nbn", "Outline"))
        self.cbGridLabels.setToolTip(_translate("nbn", "Indicate whether or not you want squares to be labelled with their grid reference."))
        self.cbGridLabels.setText(_translate("nbn", "Grid square labels"))
        self.mGroupBox.setTitle(_translate("nbn", "NBN Atlas Records Download"))
        self.pbDownload.setToolTip(_translate("nbn", "<html><head/><body><p>Download observation records from the NBN Atlas. You must specify at least one of the following filters: taxon, dataset (or data provider) or polygon.</p></body></html>"))
        self.pbDownload.setText(_translate("nbn", "Download   "))
        self.cboDownloadReason.setToolTip(_translate("nbn", "Specify a reason for NBN download"))
        self.leNbnOutputFolder.setToolTip(_translate("nbn", "Folder for atlas images"))
        self.pbBrowseNbnOutputFolder.setText(_translate("nbn", "Browse output folder"))
        self.groupBox_7.setTitle(_translate("nbn", "Specified Filters"))
        self.cbIndTaxon.setText(_translate("nbn", "Species"))
        self.cbIndDataset.setText(_translate("nbn", "Dataset"))
        self.cbIndSpeciesList.setText(_translate("nbn", "Species list"))
        self.cbIndStartYear.setText(_translate("nbn", "Start year"))
        self.cbIndEndYear.setText(_translate("nbn", "End year"))
        self.cbIndPolygon.setText(_translate("nbn", "Polygon"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOptions), _translate("nbn", "NBN"))
        self.leTaxonSearch.setToolTip(_translate("nbn", "Enter search term for taxon"))
        self.butTaxonSearch.setToolTip(_translate("nbn", "Search the UK Species Inventory"))
        self.twTaxa.setToolTip(_translate("nbn", "<html><head/><body><p>Matching taxa - check the species you want.</p></body></html>"))
        self.label_5.setText(_translate("nbn", "<html><head/><body><p>Double-click taxa to add/remove them from the filters list.</p></body></html>"))
        self.pbClearTaxonFilters.setToolTip(_translate("nbn", "Clear all filters"))
        self.pbClearTaxonFilters.setText(_translate("nbn", "Clear taxon filters"))
        self.tabFilters.setTabText(self.tabFilters.indexOf(self.tab_8), _translate("nbn", "Taxon"))
        self.twProviders.setToolTip(_translate("nbn", "<html><head/><body><p>NBN Datasets - check to filter</p></body></html>"))
        self.lblDatasetFilter.setText(_translate("nbn", "lblDatasetFilter"))
        self.pbUncheckAll.setToolTip(_translate("nbn", "Uncheck all dataset items"))
        self.pbUncheckAll.setText(_translate("nbn", "Clear dataset filters"))
        self.pbRefreshDatasets.setToolTip(_translate("nbn", "<html><head/><body><p>Update the dataset list from the NBN Atlas</p></body></html>"))
        self.pbRefreshDatasets.setText(_translate("nbn", "Refresh list"))
        self.tabFilters.setTabText(self.tabFilters.indexOf(self.tab_9), _translate("nbn", "Dataset"))
        self.lblSpeciesListFilter.setText(_translate("nbn", "lblSpeciesListFilter"))
        self.pbUncheckAllSpeciesList.setToolTip(_translate("nbn", "Uncheck all list items"))
        self.pbUncheckAllSpeciesList.setText(_translate("nbn", "Clear species list filters"))
        self.pbRefreshSpeciesLists.setToolTip(_translate("nbn", "<html><head/><body><p>Update the dataset list from the NBN Atlas</p></body></html>"))
        self.pbRefreshSpeciesLists.setText(_translate("nbn", "Refresh list"))
        self.tabFilters.setTabText(self.tabFilters.indexOf(self.tabSpeciesLists), _translate("nbn", "Lists"))
        self.groupBox.setTitle(_translate("nbn", "Year"))
        self.sbStartYear.setToolTip(_translate("nbn", "Specify start year"))
        self.cbStartYear.setToolTip(_translate("nbn", "<html><head/><body><p>Check box to filter out records before given start year.</p></body></html>"))
        self.cbStartYear.setText(_translate("nbn", "Filter out records before start year"))
        self.sbEndYear.setToolTip(_translate("nbn", "Specify end year"))
        self.cbEndYear.setToolTip(_translate("nbn", "<html><head/><body><p>Check box to filter out records after given end year.</p></body></html>"))
        self.cbEndYear.setText(_translate("nbn", "Filter out records after end year"))
        self.tabFilters.setTabText(self.tabFilters.indexOf(self.tab_13), _translate("nbn", "Dates"))
        self.groupBox_8.setTitle(_translate("nbn", "Point and buffer tool"))
        self.rbGR.setText(_translate("nbn", "Use British or Irish GR"))
        self.rbEN.setText(_translate("nbn", "Use easting/northing"))
        self.label_7.setText(_translate("nbn", "Grid ref:"))
        self.lePointBufferGR.setToolTip(_translate("nbn", "<html><head/><body><p>Specify a grid reference to use as a filter when downloading records from the NBN Gateway, or for use with the point and radius buffer creation.</p></body></html>"))
        self.label_10.setText(_translate("nbn", "Easting:"))
        self.sbEasting.setToolTip(_translate("nbn", "<html><head/><body><p>Specify an easting for use with the point and buffer convenience tool.</p></body></html>"))
        self.label_8.setText(_translate("nbn", "Northing:"))
        self.sbNorthing.setToolTip(_translate("nbn", "<html><head/><body><p>Specify a northing for use with the point and buffer convenience tool.</p></body></html>"))
        self.rbBritishEN.setText(_translate("nbn", "British"))
        self.rbIrishEN.setText(_translate("nbn", "Irish"))
        self.label_9.setText(_translate("nbn", "Buffer (m):"))
        self.sbBuffer.setToolTip(_translate("nbn", "<html><head/><body><p>Specify buffer radius in metres for use with the point and buffer convenience tool. Minimum of 10 metres and maximum of 10,000 m (10 km).</p></body></html>"))
        self.pbBuffer.setToolTip(_translate("nbn", "<html><head/><body><p>Generate circular buffer around specified point.</p></body></html>"))
        self.pbClearLastBuffer.setToolTip(_translate("nbn", "Remove last buffer"))
        self.tabFilters.setTabText(self.tabFilters.indexOf(self.tabUtilities), _translate("nbn", "Utilities"))
        self.pbClearFilters.setToolTip(_translate("nbn", "Clear all filters"))
        self.pbClearFilters.setText(_translate("nbn", "Clear all filters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("nbn", "Filters"))
        self.label_4.setText(_translate("nbn", "<html><head/><body><p>Double-clicking a data CSV item below, opens it in the biological records tool. Double-clicking a data provider or column metadata item displays it on the \'download metadata\' tab.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDownloads), _translate("nbn", "Downloads"))
        self.mGroupBox_2.setTitle(_translate("nbn", "Information"))
        self.lblMetadata.setText(_translate("nbn", "TextLabel"))
        self.cbShowAllMetadata.setText(_translate("nbn", "Show all metadata columns"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMetadata), _translate("nbn", "Download metadata"))
        self.butClearLast.setToolTip(_translate("nbn", "Remove last NBN Atlas WMS layer"))
        self.butClear.setToolTip(_translate("nbn", "Remove all NBN Atlas WMS layers"))
        self.butHelp.setToolTip(_translate("nbn", "<html><head/><body><p><span style=\" font-size:12pt;\">Get more information about this tool and help on using it. This links to a webpage with up-to-date information about the tool. </span></p></body></html>"))
        self.butGithub.setToolTip(_translate("nbn", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Report an issue with this tool.</span><span style=\" font-size:12pt;\"> Using this channel is the best way to get attention quickly. Issues can be bug reports, enhancement requests or just questions. Anyone can view current issues, but to add a new issue you will need to sign up for a free Github account (very easy).</span></p></body></html>"))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgscolorbutton import QgsColorButton
