# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_osgr.ui'
#
# Created: Sat Jan 14 14:55:29 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_osgr(object):
    def setupUi(self, osgr):
        osgr.setObjectName(_fromUtf8("osgr"))
        osgr.setEnabled(True)
        osgr.resize(287, 394)
        self.verticalLayout_2 = QtGui.QVBoxLayout(osgr)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.cboPrecision = QtGui.QComboBox(osgr)
        self.cboPrecision.setObjectName(_fromUtf8("cboPrecision"))
        self.cboPrecision.addItem(_fromUtf8(""))
        self.cboPrecision.addItem(_fromUtf8(""))
        self.cboPrecision.addItem(_fromUtf8(""))
        self.cboPrecision.addItem(_fromUtf8(""))
        self.cboPrecision.addItem(_fromUtf8(""))
        self.cboPrecision.addItem(_fromUtf8(""))
        self.cboPrecision.addItem(_fromUtf8(""))
        self.cboPrecision.addItem(_fromUtf8(""))
        self.cboPrecision.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cboPrecision)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(osgr)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.dsbGridSize = QtGui.QDoubleSpinBox(osgr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbGridSize.sizePolicy().hasHeightForWidth())
        self.dsbGridSize.setSizePolicy(sizePolicy)
        self.dsbGridSize.setDecimals(3)
        self.dsbGridSize.setMaximum(100000000.0)
        self.dsbGridSize.setSingleStep(100.0)
        self.dsbGridSize.setObjectName(_fromUtf8("dsbGridSize"))
        self.horizontalLayout.addWidget(self.dsbGridSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gbGridRef = QtGui.QGroupBox(osgr)
        self.gbGridRef.setMinimumSize(QtCore.QSize(0, 86))
        self.gbGridRef.setObjectName(_fromUtf8("gbGridRef"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbGridRef)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.leOSGR = QtGui.QLineEdit(self.gbGridRef)
        self.leOSGR.setText(_fromUtf8(""))
        self.leOSGR.setObjectName(_fromUtf8("leOSGR"))
        self.horizontalLayout_3.addWidget(self.leOSGR)
        self.butLocate = QtGui.QPushButton(self.gbGridRef)
        self.butLocate.setMinimumSize(QtCore.QSize(75, 23))
        self.butLocate.setMaximumSize(QtCore.QSize(75, 23))
        self.butLocate.setObjectName(_fromUtf8("butLocate"))
        self.horizontalLayout_3.addWidget(self.butLocate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cbGROnClick = QtGui.QCheckBox(self.gbGridRef)
        self.cbGROnClick.setObjectName(_fromUtf8("cbGROnClick"))
        self.horizontalLayout_4.addWidget(self.cbGROnClick)
        self.cbGRShowSquare = QtGui.QCheckBox(self.gbGridRef)
        self.cbGRShowSquare.setObjectName(_fromUtf8("cbGRShowSquare"))
        self.horizontalLayout_4.addWidget(self.cbGRShowSquare)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.gbGridRef)
        self.gpGridSquares = QtGui.QGroupBox(osgr)
        self.gpGridSquares.setMinimumSize(QtCore.QSize(0, 100))
        self.gpGridSquares.setObjectName(_fromUtf8("gpGridSquares"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gpGridSquares)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.butGridTool = QtGui.QPushButton(self.gpGridSquares)
        self.butGridTool.setMinimumSize(QtCore.QSize(35, 35))
        self.butGridTool.setMaximumSize(QtCore.QSize(35, 35))
        self.butGridTool.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/osgr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butGridTool.setIcon(icon)
        self.butGridTool.setIconSize(QtCore.QSize(26, 26))
        self.butGridTool.setCheckable(True)
        self.butGridTool.setFlat(False)
        self.butGridTool.setObjectName(_fromUtf8("butGridTool"))
        self.horizontalLayout_2.addWidget(self.butGridTool)
        self.butGridPoly = QtGui.QPushButton(self.gpGridSquares)
        self.butGridPoly.setMinimumSize(QtCore.QSize(35, 35))
        self.butGridPoly.setMaximumSize(QtCore.QSize(35, 35))
        self.butGridPoly.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/osgrPoly.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butGridPoly.setIcon(icon1)
        self.butGridPoly.setIconSize(QtCore.QSize(26, 26))
        self.butGridPoly.setCheckable(False)
        self.butGridPoly.setObjectName(_fromUtf8("butGridPoly"))
        self.horizontalLayout_2.addWidget(self.butGridPoly)
        self.cbLabel = QtGui.QCheckBox(self.gpGridSquares)
        self.cbLabel.setChecked(True)
        self.cbLabel.setObjectName(_fromUtf8("cbLabel"))
        self.horizontalLayout_2.addWidget(self.cbLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.butClear = QtGui.QPushButton(self.gpGridSquares)
        self.butClear.setMinimumSize(QtCore.QSize(35, 35))
        self.butClear.setMaximumSize(QtCore.QSize(35, 35))
        self.butClear.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/cross.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butClear.setIcon(icon2)
        self.butClear.setIconSize(QtCore.QSize(30, 30))
        self.butClear.setObjectName(_fromUtf8("butClear"))
        self.horizontalLayout_2.addWidget(self.butClear)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pbGridSquares = QtGui.QProgressBar(self.gpGridSquares)
        self.pbGridSquares.setProperty("value", 0)
        self.pbGridSquares.setObjectName(_fromUtf8("pbGridSquares"))
        self.horizontalLayout_5.addWidget(self.pbGridSquares)
        self.butCancel = QtGui.QPushButton(self.gpGridSquares)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butCancel.sizePolicy().hasHeightForWidth())
        self.butCancel.setSizePolicy(sizePolicy)
        self.butCancel.setMinimumSize(QtCore.QSize(0, 0))
        self.butCancel.setMaximumSize(QtCore.QSize(50, 500))
        self.butCancel.setObjectName(_fromUtf8("butCancel"))
        self.horizontalLayout_5.addWidget(self.butCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.gpGridSquares)
        spacerItem2 = QtGui.QSpacerItem(20, 170, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)

        self.retranslateUi(osgr)
        self.cboPrecision.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(osgr)

    def retranslateUi(self, osgr):
        osgr.setWindowTitle(_translate("osgr", "Form", None))
        self.cboPrecision.setToolTip(_translate("osgr", "Set the OSGR precision.", None))
        self.cboPrecision.setItemText(0, _translate("osgr", "10 figure", None))
        self.cboPrecision.setItemText(1, _translate("osgr", "8 figure", None))
        self.cboPrecision.setItemText(2, _translate("osgr", "6 figure", None))
        self.cboPrecision.setItemText(3, _translate("osgr", "Monad (1 km square)", None))
        self.cboPrecision.setItemText(4, _translate("osgr", "Tetrad (2 km square)", None))
        self.cboPrecision.setItemText(5, _translate("osgr", "Quadrant (5 km square)", None))
        self.cboPrecision.setItemText(6, _translate("osgr", "Hectad (10 km square)", None))
        self.cboPrecision.setItemText(7, _translate("osgr", "100 km square", None))
        self.cboPrecision.setItemText(8, _translate("osgr", "User specified", None))
        self.label.setText(_translate("osgr", "Grid size:", None))
        self.dsbGridSize.setToolTip(_translate("osgr", "Set a size for the grid squares in the unitsused by the current project map CRS.", None))
        self.gbGridRef.setTitle(_translate("osgr", "Grid Ref at mouse cursor", None))
        self.leOSGR.setToolTip(_translate("osgr", "<html><head/><body><p>Grid reference at mouse location or grid reference to which you want to navigate.</p></body></html>", None))
        self.butLocate.setToolTip(_translate("osgr", "<html><head/><body><p>Locate the map at the specified grid reference.</p></body></html>", None))
        self.butLocate.setText(_translate("osgr", "Locate", None))
        self.cbGROnClick.setToolTip(_translate("osgr", "<html><head/><body><p>Update grid reference only when map is clicked.</p></body></html>", None))
        self.cbGROnClick.setText(_translate("osgr", "On click", None))
        self.cbGRShowSquare.setToolTip(_translate("osgr", "<html><head/><body><p>Show grid square corresponding to grid reference. (For UK National Grid only.)</p></body></html>", None))
        self.cbGRShowSquare.setText(_translate("osgr", "Show grid square", None))
        self.gpGridSquares.setTitle(_translate("osgr", "OS grid squares", None))
        self.butGridTool.setToolTip(_translate("osgr", "<html><head/><body><p>With this tool selected, drag a box over the map to generate grid squares.</p></body></html>", None))
        self.butGridPoly.setToolTip(_translate("osgr", "<html><head/><body><p>With a feature selected, click this tool to generate grid squares over the feature.</p></body></html>", None))
        self.cbLabel.setToolTip(_translate("osgr", "<html><head/><body><p>Indicates whether or not to show labels for generated grids.</p></body></html>", None))
        self.cbLabel.setText(_translate("osgr", "Label", None))
        self.butClear.setToolTip(_translate("osgr", "<html><head/><body><p>Delete all generated grid squares.</p></body></html>", None))
        self.butCancel.setToolTip(_translate("osgr", "<html><head/><body><p>Interrupt the generation of grid squares.</p></body></html>", None))
        self.butCancel.setText(_translate("osgr", "Cancel", None))

