# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapmashup.ui'
#
# Created: Sat Aug 02 19:42:39 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Mapmashup(object):
    def setupUi(self, Mapmashup):
        Mapmashup.setObjectName(_fromUtf8("Mapmashup"))
        Mapmashup.resize(294, 352)
        self.verticalLayout = QtGui.QVBoxLayout(Mapmashup)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(Mapmashup)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leImageFolder = QtGui.QLineEdit(self.frame)
        self.leImageFolder.setObjectName(_fromUtf8("leImageFolder"))
        self.horizontalLayout.addWidget(self.leImageFolder)
        self.butBrowseImg = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butBrowseImg.sizePolicy().hasHeightForWidth())
        self.butBrowseImg.setSizePolicy(sizePolicy)
        self.butBrowseImg.setMinimumSize(QtCore.QSize(100, 0))
        self.butBrowseImg.setMaximumSize(QtCore.QSize(100, 16777215))
        self.butBrowseImg.setObjectName(_fromUtf8("butBrowseImg"))
        self.horizontalLayout.addWidget(self.butBrowseImg)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(Mapmashup)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.leRegistrationFolder = QtGui.QLineEdit(self.frame_2)
        self.leRegistrationFolder.setObjectName(_fromUtf8("leRegistrationFolder"))
        self.horizontalLayout_2.addWidget(self.leRegistrationFolder)
        self.butBrowseReg = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butBrowseReg.sizePolicy().hasHeightForWidth())
        self.butBrowseReg.setSizePolicy(sizePolicy)
        self.butBrowseReg.setMinimumSize(QtCore.QSize(100, 0))
        self.butBrowseReg.setMaximumSize(QtCore.QSize(100, 16777215))
        self.butBrowseReg.setObjectName(_fromUtf8("butBrowseReg"))
        self.horizontalLayout_2.addWidget(self.butBrowseReg)
        self.verticalLayout.addWidget(self.frame_2)
        self.cboRegistrations = QtGui.QComboBox(Mapmashup)
        self.cboRegistrations.setObjectName(_fromUtf8("cboRegistrations"))
        self.verticalLayout.addWidget(self.cboRegistrations)
        self.frame_3 = QtGui.QFrame(Mapmashup)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.butLoadImage = QtGui.QPushButton(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butLoadImage.sizePolicy().hasHeightForWidth())
        self.butLoadImage.setSizePolicy(sizePolicy)
        self.butLoadImage.setMinimumSize(QtCore.QSize(75, 0))
        self.butLoadImage.setMaximumSize(QtCore.QSize(75, 16777215))
        self.butLoadImage.setObjectName(_fromUtf8("butLoadImage"))
        self.horizontalLayout_3.addWidget(self.butLoadImage)
        self.leName = QtGui.QLineEdit(self.frame_3)
        self.leName.setObjectName(_fromUtf8("leName"))
        self.horizontalLayout_3.addWidget(self.leName)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(Mapmashup)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.frame_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.hsTransparency = QtGui.QSlider(self.frame_4)
        self.hsTransparency.setOrientation(QtCore.Qt.Horizontal)
        self.hsTransparency.setTickPosition(QtGui.QSlider.TicksBelow)
        self.hsTransparency.setTickInterval(10)
        self.hsTransparency.setObjectName(_fromUtf8("hsTransparency"))
        self.horizontalLayout_4.addWidget(self.hsTransparency)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtGui.QFrame(Mapmashup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 31))
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.butClearLast = QtGui.QPushButton(self.frame_5)
        self.butClearLast.setGeometry(QtCore.QRect(0, 0, 30, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butClearLast.sizePolicy().hasHeightForWidth())
        self.butClearLast.setSizePolicy(sizePolicy)
        self.butClearLast.setMinimumSize(QtCore.QSize(30, 0))
        self.butClearLast.setMaximumSize(QtCore.QSize(30, 16777215))
        self.butClearLast.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/removelayer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butClearLast.setIcon(icon)
        self.butClearLast.setIconSize(QtCore.QSize(30, 30))
        self.butClearLast.setObjectName(_fromUtf8("butClearLast"))
        self.butClear = QtGui.QPushButton(self.frame_5)
        self.butClear.setGeometry(QtCore.QRect(34, 0, 30, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butClear.sizePolicy().hasHeightForWidth())
        self.butClear.setSizePolicy(sizePolicy)
        self.butClear.setMinimumSize(QtCore.QSize(30, 0))
        self.butClear.setMaximumSize(QtCore.QSize(30, 16777215))
        self.butClear.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/removelayers.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butClear.setIcon(icon1)
        self.butClear.setIconSize(QtCore.QSize(30, 30))
        self.butClear.setObjectName(_fromUtf8("butClear"))
        self.verticalLayout.addWidget(self.frame_5)
        spacerItem = QtGui.QSpacerItem(20, 150, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Mapmashup)
        QtCore.QMetaObject.connectSlotsByName(Mapmashup)

    def retranslateUi(self, Mapmashup):
        Mapmashup.setWindowTitle(_translate("Mapmashup", "TomBio", None))
        self.butBrowseImg.setText(_translate("Mapmashup", "Image folder", None))
        self.butBrowseReg.setText(_translate("Mapmashup", "Registration folder", None))
        self.butLoadImage.setText(_translate("Mapmashup", "Make layer", None))
        self.label.setText(_translate("Mapmashup", "Transparency", None))

